### ISSUE TITLE
活動名稱 (已結束)

### ISSUE THREAD

**Issue by juincc0** [EtherTW/beyondblock_taipei_2017#1]
最終方案：
### BeyondBlock Taipei

可從[這裡](https://bravenewcoin.com/industry-resources/events-calendar/bitcoin-and-blockchain-events/)找靈感

**Comment by juincc0** [comment]
提案：
## Blockway Taipei

1. blockway 類似 broadway，簡單好記
2. way 擁有「方法」及「路線」兩種意思

**Comment by ChihChengLiang** [comment]
提案

## Broadcast Taipei

把台北的聲音傳出去，讓網路上的其他 peer 們知道

**Comment by quesalltime** [comment]
提案

**BlockBroad Taipei**

結合邱駿和智程提供的意象,簡稱 BBT

**Comment by changwu-tw** [comment]
BeyondBlock Taipei, also named BBT

**Comment by juincc0** [comment]
於[社團](https://www.facebook.com/groups/443751072484739/)進行投票喔
預計至 11/1

**Comment by yaochunghu** [comment]
提案
# Distributed Taipei

**Comment by tyrinwu** [comment]
建議：選一個比較好搜尋的名字？ 猜想一個想搜尋Blockchain活動的人，可能就不太會注意到這個名稱比較特別的活動（如果主辦單位沒有多餘力氣宣傳。） 
也許簡單的Blockchain Taipei Summit 之類的名稱就可以

**Comment by juincc0** [comment]
@tyrinwu 
1. 會使用不同命名是因為我們想弄一場有台灣特色的活動，或許 `Blockchain Taipei Summit` 可以當成副標題
2. 我們的 TA 偏技術端

Thanks for advising!

**Comment by tyrinwu** [comment]
@juinc 明白你們的想法。　意見提供參考:P

**Comment by juincc0** [comment]
投票結束囉，得票數如下：
- BeyondBlock Taipei: 55
- Blockway Taipei: 5
- BlockBroad Taipei: 2

因此決定活動命名為：
### BeyondBlock Taipei
