### ISSUE TITLE
預算

### ISSUE THREAD

**Issue by juincc0** [EtherTW/beyondblock_taipei_2017#10]
| 項目 | 說明 | 預算 |
| :---: | :---: | :---: |
| 場地 | 未來產房 | 36000 |
| 餐飲 | 外燴 / 茶水 / 酒水 | 50000 |
| 設計 | 貼紙/網站 | 5000 |
| 雜支 | 講者小禮物 | 5000 |
| 機票 | 台北 <=> 紐約 | 35000 |

**Comment by daubas** [comment]
11/3 還需要一張紐約到台灣的來回機票。

**Comment by daubas** [comment]
目前講者變多，
我在贊助部分把禮物用一萬元做估計。

**Comment by daubas** [comment]
1/11預算更新

項目 | 說明 | 預算 | 附註
-- | -- | -- | --
場地 | 未來產房 | 39900 |已經付款
餐飲 | 晚宴外燴 | 42600 | 880x45+3000（車資）
餐飲 | 活動中茶水，便當 | 約20000 | 
設計 | 貼紙/網站 | 1800+5000 | | 
雜支 | 講者小禮物 | 10000 | | 1000x10
機票 | 台北 <=> 紐約 | 70000 | 35000x2

出納部分由 @willliw 處理
未估計部分麻煩 @juinc 補完

**Comment by yurenju** [comment]
根據 @daubas 的 comment，我先把這個 issue assign 給 @willliw  跟 @juinc

**Comment by juincc0** [comment]
講者禮物上回是討論要送茶葉？

**Comment by juincc0** [comment]
茶水要不要問看看 Futureward 是否有配合廠商？

**Comment by juincc0** [comment]
便當廠商我回覆在 #22

**Comment by yurenju** [comment]
針對飲料廠商未來產房回覆如下：

> 我們沒有配合點心飲料的廠商，但我們很常跟這一家訂餐點：https://www.fresh-line.com.tw/

**Comment by juincc0** [comment]
@daubas 
目前已花費預算可以整理一份google doc嗎？
