### ISSUE TITLE
會議紀錄區

### ISSUE THREAD

**Issue by daubas** [EtherTW/beyondblock_taipei_2017#12]
目前以slack與hangout討論為主。

**Comment by daubas** [comment]
11/3 會議紀錄
1.Paul去聯絡陽光雲、Cobinhood、BitoEX，探詢贊助內容。
2.Robin就新的名單來排定議程

需要與 @juinc 討論的事項：
是否收門票？餐飲部份的處理方案。

**Comment by juincc0** [comment]
1. 門票目前暫時沒有定論

## 贊成收費方
- 用票價過濾TA 
- 支持社群運作

## 反對收費方
- 11月太多活動，可能降低參與意願

**Comment by juincc0** [comment]
2. 外燴王可以詢問看看？
