### ISSUE TITLE
設定報名網站 (11/13)

### ISSUE THREAD

**Issue by yurenju** [EtherTW/beyondblock_taipei_2017#13]
目前我們還沒決定報名網站，這個 issue 需要：

1. Survey 要使用哪個報名網站
2. 根據我們的資訊如活動日期、票價與簡介在報名網站上建立活動。

**Comment by yurenju** [comment]
另外設定報名網站時，需要留一些兌換碼給作為公關與貴賓票。如果可以的話，我希望先拿五張給之前我有參加去政府部門開會的人，鼓勵他們來參加以太坊區塊鍊技術性活動。給了兌換碼他們不見得會來（畢竟是在假日的活動），不過還是希望這樣做。

**Comment by juincc0** [comment]
1. kktix 似乎在tech conf圈比較流行
2. 票可分幾種：貴賓/贊助/媒體/一般，給公司的票可以歸為贊助票(有收費前提下)

**Comment by juincc0** [comment]
票務這邊我處理

**Comment by daubas** [comment]
會留票給贊助廠商的話、我就列入對外的贊助文件中？是給兩張票嗎？

**Comment by daubas** [comment]
討論後目前就以兩張票為主。

**Comment by juincc0** [comment]
報名連結設定好囉
https://ethtaipei.kktix.cc/events/bbt2017

**Comment by yurenju** [comment]
@juinc 一忙就忘了問，我在上面有提到希望可以給上次跟政府部門開會的人幾張票，希望他們有機會可以參加。後來看一下贊助票大多都拿兩張，我之前說五張好像也太多了。有機會可以拿到兩張票留給政府部門的人嗎？

> 另外設定報名網站時，需要留一些兌換碼給作為公關與貴賓票。如果可以的話，我希望先拿五張給之前我有參加去政府部門開會的人，鼓勵他們來參加以太坊區塊鍊技術性活動。給了兌換碼他們不見得會來（畢竟是在假日的活動），不過還是希望這樣做。

**Comment by juincc0** [comment]
@yurenju 以表單的計算結果來看，不含政府的人數已達50，若多幾張應該就是現場多塞幾張椅子，數量若少於10 應該是可以

**Comment by yurenju** [comment]
@juinc 那我先預留兩張，並且填到 [試算表](https://docs.google.com/spreadsheets/d/1pfb_AcJV_IHBDyUbR28MyhiMeM9HX9CBYwmkBH3w9-s) 裡面，謝謝 :D
