### ISSUE TITLE
網路宣傳以線下社群宣傳

### ISSUE THREAD

**Issue by yurenju** [EtherTW/beyondblock_taipei_2017#14]
依照目前的重要時間的進度，我們應該開始進行宣傳。先列出幾個重要的時間：
* 網站上線：11/6
* 報名開始：11/13
* 活動當天：11/25

### 宣傳目的

本次宣傳的目的有幾個：

1. 希望在台灣對區塊鍊技術有興趣的人（以技術為主）都可以知道這個活動並且知道這次研討會的講師與議程並且在開始報名的那天可以盡快地來報名。
2. 當報名截止後，還會希望有進一步的曝光，讓沒有搶到票的人，知道活動當天開始後可以到直播頻道觀看這次活動。

宣傳目的中最重要的就是第一點，所以宣傳工作應於報名開始前展開，並且在一定時間內維持曝光程度。讓所有有興趣的人都不會錯過報名時間。

#### 線上
根據以上的目的，我們應該有計劃地在 Ethereum Meetup 社群發送貼文，並且盡可能的增加觸及觀眾，達到上述目的。目前構想的宣傳貼文如下：

1. **網站上線前**：在網站上線的前幾天預告，目的為增加大家的好奇心，知道這次的活動調性為技術導向。
2. **網站上線當天**：網站上線時同時貼文宣傳網站上線的消息，重量級的講者在此也會同時曝光，貼文內應該要提及數個重量級講者的名字與來頭。
3. **網站上線到開始報名之間**：此時網站已經上線，我們可以每天貼上一個講者的講題與簡介，逐漸地醞釀大家想來聽演講的氣氛，並且由此增進貼文分享頻率，同時也可以不斷提醒報名開始的時間。
4. **開始報名到活動開始**：這段時間報名已經結束，可以貼一些比較輕鬆的貼文，像是一些介紹區塊鍊予以太坊的基礎資訊或是大會開始前想要讓大家知道的資訊等等。

**註**：貼文時間最好是在上班通勤時貼文，大家在最會滑手機的時候看到這則消息，可以增加曝光度。

#### 線下宣傳

如果這個期間有任何區塊鍊的社群聚會，如果時間與地點允許的話，希望可以聯絡他們，撥幾分鐘的時間給我們宣傳本次活動。

### 宣傳稿與其他事項

宣傳稿件跟上線時間會直接貼在這個 issue 裡面，而這個 issue 則會在宣傳期結束之後關閉。也徵求各種線上社群與現下活動的名稱與連結。

* [熵熱踢道場DLTDOJO](https://www.facebook.com/groups/dltdojo/)

**Comment by yurenju** [comment]
### 宣傳稿 11/6
這幾天值得祝賀的事除了 PTT 復站外，Taipei Ethereum Meetup 也要辦研討會囉！BeyondBlock Taipei 將會是一個聚焦於區塊鍊的技術型單日研討會，網站與議程近期即將上線！說到以太坊 Ethereum，你最想聽的講者是誰呢？搞不好他即將來台演講呦 🌈  

#真的很想知道Ｔ恤哪裡買的
#不管他嗑了什麼都給我來一點
#BeyondBlock #BeyondBlockTaipei2017

![image](https://user-images.githubusercontent.com/22155/32412658-7a655d74-c239-11e7-8888-730990b89931.png)

**Comment by juincc0** [comment]
1. 圖有創意，但這個梗會不會很多人不知道
2. 台北以太坊社群 => Taipei Ethereum Meetup
3. 可以下面弄一些有趣的hashtag ex: 不管他嗑了什麼都給我來一點

**Comment by yurenju** [comment]
因為報名網站理論上這一兩天應該就會開張了，所以這兩天先貼一些暗示性的圖，讓大家猜猜培養一下好奇心跟期待感，兩天後一公布網站，到時候會在強力放送 Vitalik 來台演講的消息。另外 (2) 的話我等等直接改在宣傳稿裡面

**Comment by yurenju** [comment]
上面這則貼文我就排定到周一 11/6 貼囉。晚點會再寫幾則推廣貼文到這邊。粉絲團可以排程貼文，我會把他排在 11/6 早上九點發。另外我稍微研究了一下粉絲團的貼文建議，上面字數可能會太多，我看看可不可以再減少一點。

**Comment by yurenju** [comment]
### 宣傳稿 11/7

沒錯以太坊區塊鍊創辦人 Vitalik 即將於 11/25 來台演講啦！！我們的官網也同步公開！除此外還有夢幻陣容的講者如 Vlad Zamfir, Karl Floersch 等帶領以太坊社群的關鍵人物都將來台演講，不想錯過的朋友別忘了關注粉絲團以及官方網站，報名時間近期即將公布！ 
🚀🚀 官方網站： https://ethertw.github.io/bbt2017/

#好奇Vitalik會穿什麼Ｔ恤來台
#BeyondBlock #BeyondBlockTaipei2017

![bbt2017-speakers](https://user-images.githubusercontent.com/22155/32445371-80000970-c340-11e7-809e-66b3b9103fdb.jpg)

**Comment by yurenju** [comment]
### 宣傳稿 11/8

🚀 官方網站上線啦！除了昨天已經公布的講者內容外，議程也公開了，趕快去看看吧！別忘了空出 11/25 週六，讓我們在台北跟超強講者們一起深入區塊鍊技術！報名資訊近期也即將公布！

https://ethertw.github.io/bbt2017/

**Comment by yurenju** [comment]
![image](https://user-images.githubusercontent.com/22155/32501558-4c873b26-c413-11e7-9bbd-366e5d149cdd.png)

今天的分析報告，看起來還不錯，上篇文章的流量也跟著帶起來了。接下來預計會有幾個比較重要的宣布：

1. 網站公布 - 明天
2. 報名日期時間公布 - TBD
3. 報名當天 - TBD

這三個時間點理論上會比較多觀眾，剩下的貼文我會用講者介紹大約一兩天貼一篇保持一些熱度，但是就不會像上面這三個時間點的貼文這麼熱。

**Comment by yurenju** [comment]
### 宣傳稿 11/9

想必大家都磨刀霍霍的想報名了吧？報名時間很快就會公開囉！話說大家有注意到 Vitalik Twitter 上的叉子圖嗎？原來這是在 Ethereum Foundation 成員聚會上，粉絲送給他上面寫著 " Byzantine #4,370,000" 的硬叉子 (Hard Fork) 慶祝分岔成功唷，話說這世上也沒有什麼軟叉子啦  😏

#報名時間即將公布
#記得先把1125空下來阿
#BeyondBlock #BeyondBlockTaipei2017

![acyhc0ynk](https://user-images.githubusercontent.com/22155/32582208-99d3287a-c528-11e7-9348-c2d6e92e3348.jpg)

**Comment by yurenju** [comment]
最近這幾波發文都不錯，也把之前貼文的觸擊率拉上來了。不過前幾天的貼文都算蠻重要的資訊，今天的貼文則屬於冷知識，就要看大家有沒有覺得有有趣願意分享了 XD

![image](https://user-images.githubusercontent.com/22155/32582525-45b44ca4-c52a-11e7-9e69-cd44c2876a16.png)

**Comment by yurenju** [comment]
### 11/11 宣傳稿

📆📆各位觀眾！最重要的報名時間終於姍姍來遲啦！除了最重要的報名日期 11/13 中午十二點外，本次 BeyondBlock 開放的報名人次僅有 100 人，如果不想錯過這個華麗的講者陣容，現在馬上設定手機上的提醒吧！⏰

報名網站（尚未開賣）： https://ethtaipei.kktix.cc/events/bbt2017
#BeyondBlock #BeyondBlockTaipei2017

![save-the-date](https://user-images.githubusercontent.com/22155/32616746-16a8d09a-c5ae-11e7-8946-1d903a223f0a.png)

**Comment by hwwhww** [comment]
微修

📆📆各位觀眾！最重要的報名時間終於出來啦！除了最重要的門票將在 11/13 中午十二點開放搶票，本次 BeyondBlock 開放的門票數量僅有 100 人！如果不想錯過這個華麗的講者陣容，現在馬上設定手機上的提醒吧！⏰

報名網站（尚未開賣）： https://ethtaipei.kktix.cc/events/bbt2017
#BeyondBlock #BeyondBlockTaipei2017

**Comment by yurenju** [comment]
依照上面版本修改門票數量，因為怕複製錯所以多 copy 一份 XD

📆📆各位觀眾！最重要的報名時間終於出來啦！除了最重要的門票將在 11/13 中午十二點開放搶票，本次 BeyondBlock 開放的門票數量僅有 80 人！如果不想錯過這個華麗的講者陣容，現在馬上設定手機上的提醒吧！⏰

報名網站（尚未開賣）： https://ethtaipei.kktix.cc/events/bbt2017
#BeyondBlock #BeyondBlockTaipei2017

**Comment by yurenju** [comment]
### 11/13 宣傳稿

今天中午十二點就是 BeyondBlock 研討會的報名時間了，想聆聽夢幻陣容的演講千萬不要錯過啊！

📆 售票： https://ethtaipei.kktix.cc/events/bbt2017
📢 官網： https://ethertw.github.io/bbt2017/

![giphy](https://media.giphy.com/media/C0NhnyKT89QdO/giphy.gif)

**Comment by RobinHung** [comment]
活動前有一天的宣傳應該是要提醒觀眾記得自備電腦，因為當天會有smart contract的教學，然後一定要充飽電(因為場地幾乎沒有插座可使用)

**Comment by yurenju** [comment]
@RobinHung  好！

**Comment by daubas** [comment]
之前好像說因為人太多而且要直播，
可能不開放會眾wifi密碼。
contract教學需可能考慮會眾沒網路的狀況。

**Comment by yurenju** [comment]
另外也會需要宣傳直播連結

**Comment by yurenju** [comment]
@changwu-tw 在 https://github.com/EtherTW/beyondblock_taipei_2017/issues/29#issuecomment-345705144 提到接下來兩次宣傳可以感謝一下贊助商。

**Comment by yurenju** [comment]
### 11/22 宣傳稿

各位，週末的 BeyondBlock 正在如火如荼的籌劃，目前預定直播的連結也都已經準備好了，當天預計透過直播觀看的朋友可以從下面的連結到 Youtube 頁面並且先按下「設定提醒」唷！
　
https://goo.gl/jshHtd
　
另外本活動可以順利的展開，也要感謝贊助這次活動的企業 AMIS, 陽光雲, BitoEX, Cobinhood, 鯨鏈科技, 共識科技, LO3 Energy 的支持，沒有他們就沒辦法帶給大家這麼好的活動了，感謝他們的支持！

<img width="974" alt="taipei_ethereum_meetup_-_youtube_-_youtube_-__ _" src="https://user-images.githubusercontent.com/22155/33084163-31da9f84-cf1c-11e7-94f0-5530190ae9c5.png">

<img width="668" alt="default" src="https://user-images.githubusercontent.com/22155/33083608-ca1ab5ba-cf1a-11e7-9ed3-00e408b25e6f.png">

**Comment by yurenju** [comment]
這個 issue 在明天發完最後一次的宣傳後也會關閉～耶～～～ \o/

**Comment by hwwhww** [comment]
當直播開始後要不要在 reddit 上 po 連結呀？

**Comment by hwwhww** [comment]
想了三秒，以前好像也是有人提早 po 的

**Comment by ChihChengLiang** [comment]
### 台灣首次技術型區塊鏈研討會 BeyondBlockTaipei 圓滿落幕

台灣首次世界級的技術型區塊鏈研討會 `BeyondBlockTaipei`，在 2017 年 11 月 25 日於未來產房南京復興舉行。本次會議榮幸邀請到以太坊研究團隊(Ethereum Research)、國際其他知名團隊(如 imToken、Kyber Network、Raiden Network 及 OmiseGO)、本土廠商、開發者、愛好者同台交流。活動由台北以太社群（Taipei Ethereum Meetup）成員在台籌劃，並由在台的以太坊研究團隊工作成員邀請並接待嘉賓來台，旨在深化台灣參與國際區塊鏈生態的連結。

以太坊研究團隊，早上 Lane Rettig 提供入門的介紹，緊接 Karl Floersch 帶來現場的智能合約教學，下午 Vlad Zamfir 介紹區塊鏈治理，以及最後 Vitalik Buterin 的壓軸介紹 Ethereum 2.0，討論更多以太坊未來的研究與挑戰。

來自中國的 imToken 團隊第一次來到台灣，過去一直專注於開發加密貨幣的手機錢包應用，創辦人何斌首度發表 imToken 2.0 版本，在其新版本中，支援去中心化交易所、基於智能合約的閃兌模式（讓不同代幣能夠瞬間轉換）、掛單交易模式、以及更好用的 DApp 瀏覽器。目前 imToken 在台灣有一萬使用者，也將支援繁體中文與台幣。

來自德國的 BrainBot 公司，以提升區塊鏈交易速度的雷電網路（Raiden Network）專案聞名，其駐上海代表 Philipp Seifert 介紹 μRaiden (Micro Raiden) 技術，旨在提供交易雙方快速、免費、不需信任的代幣轉移，而 μRaiden 也將在下週上主鏈。

Kyber Network 的創辦人 Loi Luu，也是以太社群中著名的開發者與研究員，曾經發表多篇頂級會議論文探討智能合約的安全性、分片技術以及去中心化的礦池。Kyber Network 為他近期的專案，力在推動去中心化交易所，以更安全更高效的方式，讓使用者能夠安心購買代幣，而無需擔心中心化交易所受到單點攻擊以及私鑰託管的風險性。

OmiseGO 是早期實作 Plasma 技術的公司。 Plasma 是 Joseph Poon 與 Vitalik Buterin 於今年八月提出的技術，旨在以充分利用鏈下運算與減少資料上鏈，讓智能合約的執行達到 Visa 等級速度。

BeyondBlockTaipei 活動總召邱駿表示：「作為台灣首次聚焦區塊鏈技術的研討會，不僅將最前沿的區塊鏈研究帶進台灣，也使台灣的開發者與世界級的研發團隊進行深度的交流，感謝所有台北以太坊社群成員的努力與行動。」台北以太坊社群也將持續舉辦每月一次的技術交流，再請訂閱粉絲團取得相關訊息。


### 活動錄影與直播連結

- [上午場](https://www.youtube.com/watch?v=md9iNDdAmVo)
- [下午場](https://www.youtube.com/watch?v=9RtSod8EXn4)

### 照片

- 雅信相簿：欲使用 [本相簿](https://photos.app.goo.gl/rpHDS3bO2sE5vZLn2) 的照片於報導中，請註明「攝影：黃雅信」
- MISC 科學與人文 [相簿](https://www.flickr.com/photos/miscrec/sets/72157663015434808/with/38618036432/)
- 會眾自行上傳 [相簿](https://photos.app.goo.gl/dhTs3YyO2PXluFda2)

其他參考資料： https://hackmd.io/MYRgZgbCAmwJwFpoFMYICwgKzAQIwHYsQEAGKAQ1LDjxgryA?both

![38618036432_0f63278cae_k](https://user-images.githubusercontent.com/3391420/33240863-73627fd2-d2f8-11e7-962c-0f5671b608f2.jpg)
