### ISSUE TITLE
講者資訊

### ISSUE THREAD

**Issue by RobinHung** [EtherTW/beyondblock_taipei_2017#15]
### Vitalik Buterin
* [Personal Website](http://vitalik.ca)
* [Github](https://github.com/vbuterin)
* [Twitter](https://twitter.com/VitalikButerin)
* [Medium](https://medium.com/@VitalikButerin)

### Karl Floersch
* [Personal Website](https://karl.tech)
* [Github](https://github.com/karlfloersch)
* [Twitter](https://twitter.com/karl_dot_tech)
* [Medium](https://medium.com/@karl_dot_tech)

### Loi Luu
* [Personal Website](http://www.comp.nus.edu.sg/~loiluu)
* [Github](https://github.com/loiluu)
* [Twitter](https://twitter.com/loi_luu)
* [Medium](https://medium.com/@loiluu)

### 何斌Ben (目前找不到個人訊息，求支援)
* [imToken official](https://token.im)
* [ethfans](http://ethfans.org)

### Vlad Zamfir
* [Github](https://github.com/vladzamfir)
* [Twitter](https://twitter.com/VladZamfir)
* [Medium](https://medium.com/@Vlad_Zamfir)

### Lane Rettig
* [Twitter](https://twitter.com/lrettig)
* [LinkedIn](https://www.linkedin.com/in/lanerettig/)

### Raiden Network (待補充)
* [Official](https://raiden.network)

See also #6

**Comment by juincc0** [comment]
1. Lane 是人名？全名是？
2. Raiden network 是由哪位講者發表？
3. 若無個人資訊就先放公司連結
4. 剛看了一下網站 speaker 這個部分，似乎可以多補幾個icon連到socail media

**Comment by RobinHung** [comment]
@juinc Lane跟Raiden Network的部分已經跟昶吾詢問了，晚點會補上

**Comment by hwwhww** [comment]
Lane Rettig
https://www.crunchbase.com/person/lane-rettig

**Comment by hwwhww** [comment]
imToken 人家叫何斌

**Comment by RobinHung** [comment]
感謝，已修正

**Comment by changwu-tw** [comment]
雷電網路, 會有 Philipp 參加, Jannik 也許也會一起參與, 可能會有 micropayment, 或是在 devcon3 的 demo. 講者資訊, 他們會再寄過來...

**Comment by yurenju** [comment]
@changwu-tw 這個項目還有什麼工作需要進行的嗎？如果還有工作需要進行的話，可以先 assign 一位獲多位工作人員作為負責人，如果沒有工作要進行就可以關閉這個 issue 了 :D

**Comment by juincc0** [comment]
應該可關閉囉
