### ISSUE TITLE
議程改期 26 號評估

### ISSUE THREAD

**Issue by ChihChengLiang** [EtherTW/beyondblock_taipei_2017#16]
支持理由：

- 講者如 Karl 衝到 11/23 感恩節， 25 號很趕，會衝擊到講者前來的意願。
- Vitalik 25 號才到台灣，行程也很趕

反對理由：

- 場地、宣傳大地震
- Loi有可能26走
- 11/26 有另一個區塊鏈大會

**Comment by juincc0** [comment]
1. Karl 目前預計幾號到台北？
2. Vitalik 預計幾點到台北？

**Comment by ChihChengLiang** [comment]
Vitalik 25 號早上到，下午趕過來這樣

**Comment by juincc0** [comment]
1. Vitalik 的問題比較小，台北<=>機場頂多90分鐘 (保守)
2. Karl 他目前的schedule我們可能要先知道一下，只延後一天好像影響不大，我傾向不改期，除非所有講者都有感恩節的issue

**Comment by changwu-tw** [comment]
1. V 會有 AMIS 的人幫忙從機場接送 (感謝 Alex 的安排)
2. Karl 還在找機會跟爸媽說感恩節的事

**Comment by changwu-tw** [comment]
Closed, 仍維持 25 舉辦
