### ISSUE TITLE
講者問題集 / 採訪問題集

### ISSUE THREAD

**Issue by BrianPHChen** [EtherTW/beyondblock_taipei_2017#17]
因應我們會有文字媒體，影視媒體的採訪，加上可能觀眾對V神有技術上的問題，就統一集中在這裡讓大家幫忙收集問題．

我先列幾個問題

1. 第一次來台灣嗎？對台灣的印象．
2. 一開始對區塊鏈感興趣的契機．
3. 台灣越來越多區塊鏈開發者，對於新手有什麼建議？

**Comment by ChihChengLiang** [comment]
整理一下 ethnews 都問什麼問題，給大家靈感
https://www.ethnews.com/devcon3-ethnews-exclusive-with-vitalik-buterin

問 Ethereum 的文化
> M: What would you say is the culture of Ethereum?

問少數族群

> M: Are there regions of the world that are underrepresented? 
> M: Would you be interested in having people from those regions join the development team?

如何自學、模仿

> M: What are you teaching yourself right now?
> M: Is that something that you’ve tried to emulate?
> M: What books do you enjoy?
> M: On a lighter note, what’s your favorite subreddit?

問家庭

> M: What’s your dad’s influence been on your life?
> M: Are there any ideological differences between you and your dad?

問以太、Token

> M: Why is the issuance of Ether capped at 18 million per year?
> M: Will the issuance cap change with proof-of-stake?
> M: How would you value a token?
> M: What about fundamental valuations?
> M: Are you scared of the hype around token offerings?
> M: That still seems like a pretty low barrier to entry.
> M: Do you foresee quantum computing as a problem?
> M: Are there any projects that are especially promising right now?

問願景

> M: In a perfect world, where do you see the Ethereum ecosystem 20 years from now?

問媒體

> M: What would you like to see covered more by cryptocurrency journalists?

快問快答

> M: Let’s finish with a little game. You get two passes.

奇怪問題
> M: Is there a point at which people are no longer productive members of society?

**Comment by ChihChengLiang** [comment]
怕大家害羞丟問題上來會跳通知，放在 [hackmd](https://hackmd.io/KYNmCYE4HYEMBYC08CMBWJ8QgMaMgGbgBGiADLGQBwhoDMKkkO0QA===?both) brainstorming 吧

**Comment by juincc0** [comment]
最後結論好像是各自採訪，所以不統問統訪
