### ISSUE TITLE
第二次場勘

### ISSUE THREAD

**Issue by yurenju** [EtherTW/beyondblock_taipei_2017#18]
這邊先放一下大家這次場勘時想要獲得的資訊，以及放場勘後的筆記，這次場勘時間為 11/10 (五) 晚上七點在[未來產房](https://goo.gl/maps/Gi3wi8qEc2q)。

這次比較不一樣的是因為他們早班工作人員在六點半就下班了，晚上只會有工讀生，所以如果有一些問題不見得有辦法回答我們，不過我可以記錄下來之後問 Stephanie。

### 場地相關
- [ ] 場地位置：外燴位置，三個廠商攤位（BitoEX，陽光雲，鯨鏈科技），報到處。
- [ ] 場佈規劃：現場海報製作？工作人員與講師廠商餐飲問題
- [ ] 會眾動線
- [ ] 電源插座位置以及需要準備的延長線數量
- [ ] 問海報可以貼在哪邊，也考慮需不需要易拉寶（就是那種卷軸狀，但是可以展開的長型海報）
- [ ] 工作人員與廠商票座位
- [ ] 直播 best practice (Charlie現場教學)
- [ ] 講者晚宴動線安排

### 其他
- [ ] 贊助收款管道
- [ ] 那位講者需要機票？
- [ ] 講者禮物
- [ ] 我們自己的紀錄組？
- [ ] 議程中的工作坊安排方式（一小時實作那場）
- [ ] 討論[票數分配](https://ethertw.slack.com/archives/G7QBCLHMG/p1510244305000121)

### 寫信去問就好的項目
- [ ] 確認螢幕輸出的 adapter 未來產房有提供那些（這個我事前問他們好了）

**Comment by daubas** [comment]
這次場勘有難得有機會比較多人聚集，
在這邊列一下可能要討論的事項，
大家有要討論的事歡迎加入。

- 場地位置：外燴位置，三個廠商攤位（BitoEX，陽光雲，鯨鏈科技），報到處。

- 場佈規劃：現場海報製作？工作人員與講師廠商餐飲問題

- 贊助收款管道

想到再補..

**Comment by yurenju** [comment]
* 會眾動線
* 電源插座位置以及需要準備的延長線數量
* 確認螢幕輸出的 adapter 未來產房有提供那些（這個我事前問他們好了）
* 問海報可以貼在哪邊，也考慮需不需要易拉寶（就是那種卷軸狀，但是可以展開的長型海報）

**Comment by daubas** [comment]
- 那位講者需要機票？
- 講者禮物
- 我們自己的紀錄組？
- 工作人員與廠商票座位

**Comment by juincc0** [comment]
- 直播 best practice (Charlie現場教學)
- 講者晚宴動線安排

**Comment by daubas** [comment]
- 議程中的工作坊安排方式（一小時實作那場）

**Comment by yurenju** [comment]
把大家想要確認的項目變成 checklist 放在敘述了，大家七點門口見囉！

**Comment by yurenju** [comment]
依照昨天場勘的結果，在場地工作的部分還有一些工作需要後續處理：
* 問問有沒有背板
* 有沒有場地塞 130 張的照片
* 需要 badge 
* 贊助商 需要延長線
* 海報印刷需要人負責
* 訂便當的事務
* 要先跟便當店告知便當數量

因為場勘已結束，這個 issue 就關了

**Comment by yurenju** [comment]
昨天比較早離開所以只有跑過場地的工作事項，@daubas 可以請你把後續討論時還需要什麼 follow-up 的 task 也寫上來嗎？

**Comment by daubas** [comment]
還需處理的後續工作
- 要決定現場主持人 由 @juinc 處理
- 要安排現場場控組，處理
1.報到
2.午餐便當（餐飲葷素）
3.參加者管制（初步討論以報到時發貼紙作為參加者識別）
- 晚宴佈置尚未決定
- 有提到希望設一個訪問區在外面那區，可以進行簡單的採訪並錄影。
- 講者接待尚未有定論

我也會把有結果的放在各組負責人的issue
