### ISSUE TITLE
貼紙

### ISSUE THREAD

**Issue by ChihChengLiang** [EtherTW/beyondblock_taipei_2017#19]
版型如下，歡迎投票

**Comment by ChihChengLiang** [comment]
文字版
![image](https://user-images.githubusercontent.com/3391420/32642317-14c3ed42-c599-11e7-922f-cd50b6c9cb76.png)

**Comment by ChihChengLiang** [comment]
無文字版
![image](https://user-images.githubusercontent.com/3391420/32642322-23a1320c-c599-11e7-93fc-d02dc9db1db6.png)

**Comment by ChihChengLiang** [comment]
![image](https://user-images.githubusercontent.com/3391420/32645094-0f63c586-c5ab-11e7-9445-4acfb9745999.png)


![image](https://user-images.githubusercontent.com/3391420/32645065-f74d5084-c5aa-11e7-9e62-0d50060adedb.png)

**Comment by ChihChengLiang** [comment]
貼紙出貨。
另外百變怪小編詢問是否願意分享作品。
若沒什麼問題，晚上十點前我就留粉絲團網址，並回覆可以囉。

> 您好，我是百變怪小編，您的訂單今天寄出，想請問能在我們百變怪的ＩＧ和粉絲團分享您的作品嗎？如果可以您也能留下相關連結或名稱讓我們ＴＡＧ您喔，感謝您的訂購。

**Comment by juincc0** [comment]
沒問題唷

**Comment by yurenju** [comment]
這個工作項目在接收到貼紙後應該就沒什麼問題了，謝謝 @ChihChengLiang 的幫忙，先關了 ^^
