### ISSUE TITLE
海報

### ISSUE THREAD

**Issue by ChihChengLiang** [EtherTW/beyondblock_taipei_2017#20]
### 影響到

- 贊助商想要 follow 海報風格

### 舊版海報

- [原檔_肥.jpg](
https://drive.google.com/file/d/0B8UpUHPqsiwJSTQ5SHoyNks2T0U/view?usp=drivesdk)
- 大小： A1

![image](https://user-images.githubusercontent.com/3391420/32712685-878ddf58-c80b-11e7-8b93-f8d1613d4310.png)

### 海報上要有的資訊

- 活動名稱
- 場地
- 時間
- 主辦單位
- 贊助廠商
- 官網 QR code

**Comment by ChihChengLiang** [comment]
舊版海報我有五張，現場貼起來像這樣

https://photos.app.goo.gl/rjmy719mFDEyFKci1

**Comment by juincc0** [comment]
我想需要，或許主風格就用現有 banner?
下面主辦/協辦/贊助掛上去就好？
不過這部分有人能協助設計嗎

**Comment by ChihChengLiang** [comment]
maybe kk? 順便使用 kk 的新 banner ?

**Comment by juincc0** [comment]
@ChihChengLiang 
好喔 設計出來了嗎

**Comment by yurenju** [comment]
這個項目目前還剩下的工作有：

- [ ] 取得海報檔案（應該是在設計中？）
- [ ] 確認輸入數量
- [ ] 列印海報

**Comment by ghost** [comment]
KK here!
I will be responsible for 海報設計 and I will send out on Wed night. @ChihChengLiang @yurenju @juinc ? How do I become the assignee?

**Comment by yurenju** [comment]
@ChihChengLiang can you add @bichenkk as a member of EtherTW?

**Comment by ghost** [comment]
I need further information @@
活動名稱 => BeyondBlock Taipei 2017
場地 => FutureWard – Central
時間 => 25 November
主辦單位 => Taipei Ethereum 
贊助廠商 => list of sponsors please ????? 
官網 QR code => which website ?????

**Comment by juincc0** [comment]
活動名稱 => BeyondBlock Taipei 2017
場地 => FutureWard – Central
時間 => 25 November
*主辦單位 => Taipei Ethereum Meetup
*贊助廠商 => 官網有完整清單
*官網 QR code => https://ethertw.github.io/bbt2017/

**Comment by ChihChengLiang** [comment]
我把海報的檔案整理在這個 [資料夾](https://drive.google.com/open?id=10Lx58ATE4evIrOHql25vkk72A23HtmVy) 上

**Comment by mhchia** [comment]
已送印，A1 size，共 15 張
星期二可拿到 :)
