### ISSUE TITLE
行前會Hangout需要討論事項 (11/20 2100)

### ISSUE THREAD

**Issue by daubas** [EtherTW/beyondblock_taipei_2017#21]
時間：11/20 2100

1. 確認各組工作進度
2. 討論細流 (以議程為主線，各組支線)
3. 討論重大議題

## 贊助
- 廠商立牌 / 背板 / 訪問區

## 財務
- 機票補助
- 廠商場佈時間？

## 器材
- badge (有分版本?) / 座位名牌
- 海報
- 延長線數量
- 有無wifi
- 剪刀 / 膠帶?

## 議程
- 最終會眾名單 / 總人數 / 座位不夠的問題
- 當日報到流程 / 接待流程 / 講者上台流程
- 出入管制方式
- 講者禮物
- 行前通知
- 講者休息室的討論

## 餐點
- 中餐便當登記 / 用餐方式
- 晚宴佈置 (擺餐桌子需60*180cm 六張)

## 工作人員
- 素面白色上衣/黑色(或深色)褲 + badge

**Comment by yurenju** [comment]
場地的 2, 3 已經寄信詢問。上面的事項如果可以事前處理，不是當天才要處理的我先開成 issue，比較好釐清哪些工作已經有人認領了。

**Comment by RobinHung** [comment]
行前會要不要再提早一點啊？像是禮拜五晚上(11/17)？
不然事情感覺還有點多，怕等到11/20才討論一些事情的話會太趕

**Comment by yurenju** [comment]
我覺得目前有開出來的工作項目都應該要先做，如果有漏掉的也都開上去。行前會應該只是確認一下目前進行中的工作是不是都有 on track。就如同 @RobinHung 講的一樣，如果到時候再處理就會太慢，可以先做的就先做了，到時候只要 check 狀態即可。

**Comment by yurenju** [comment]
場地塞滿 130 張椅子的照片：

![s__75948035](https://user-images.githubusercontent.com/22155/32768970-fc7a3e48-c954-11e7-8b93-8ffaed4a113b.jpg)
![s__75948034](https://user-images.githubusercontent.com/22155/32768972-fef31d5c-c954-11e7-91a4-72a29fe61c05.jpg)

背板他們不提供我們在未來產房看到的背板，上面再放我們的海報，但是有兩個小立台可以借我們

![s__40984608](https://user-images.githubusercontent.com/22155/32769205-e7beaf74-c955-11e7-8551-9e27bf08ff39.jpg)

**Comment by yurenju** [comment]
行前會應該會由 @juinc 召集，我先把這個 issue assign 給你~

**Comment by daubas** [comment]
增加一個項目：

- 講者休息室for午餐與置物

**Comment by juincc0** [comment]
行前會定在 11/20(一) 9pm?

**Comment by daubas** [comment]
11/20會議紀錄：
- 確認各組工作進度

議程：確認各個講者[接待狀況](https://github.com/EtherTW/beyondblock_taipei_2017/issues/31)
設計：貼紙完成，海報製作中，名牌週二開始製作
網站：工作人員大頭由 @juinc 從FB上放入照片，需要修改的自行聯絡 
行銷：行前通知、各組大致完成。
直播：須製作橫幅圖檔 @ChihChengLiang ，網路直接接cable。
記錄：  @ChihChengLiang 的女友整場紀錄+各種大家隨手拍
贊助：結束 。
公關：邀請名單已接近確認完成。
財務：現況、需報帳的請由slack中pin住的檔案進入。
場務：需要人手管理
1. 接待處
2. 中午便當場佈
3. 進出場管制
晚宴安排由 @juinc 處理

- 雜項：
廠商立牌放在接待處， 背板 / 訪問區由有需求的自行找機會處理
器材：需要大家支援延長線、剪刀、膠帶、筆等等用品
海報/badge (有分版本?) / 座位名牌 @tailingchen 處理
wifi：預定全面開放
會眾名單：完成
當日報到流程 / 接待流程 / 講者上台流程 @juinc 當天與主持處理
講者休息室門卡優先接待組持有 @RobinHung 
工作人員：素面白色上衣/黑色(或深色)褲 + badge


那邊有缺漏還請補上。
