### ISSUE TITLE
便當事宜

### ISSUE THREAD

**Issue by yurenju** [EtherTW/beyondblock_taipei_2017#22]
當天目前決定是要提供便當，有幾件事情要完成：

- [x] 確認便當數量
- [x] 決定便當廠商後，聯絡廠商確定 (1) 當天可出這個數量的便當 (2) 葷素當天問來不來得及 (3) 要幾點前跟他說便當數量
- [ ] 當天確定葷素食後，連絡便當廠商

**Comment by daubas** [comment]
處理中餐的需要去針對講者需求客製化@@

infomation via @hwwang
（保母大媽）對於餐飲的小小 hint～
我們有一些挑食的 VVVIP，有人只吃肉不吃澱粉，有人不喝咖啡但會喝無糖的茶，有人不吃甜食除了 90% 以上的黑巧克力....
（雖然這些人，很可能也不會乖乖待著吃 QQ 所以我立場薄弱）

**Comment by juincc0** [comment]
這家看起來不錯
[麥斯盒子](https://www.facebook.com/pg/ComfortaBox/shop/?rid=1667452780161159&rt=6)
菜色蠻豐富，看起來漂亮，而且健康
<img width="828" alt="2017-11-14 10 09 27" src="https://user-images.githubusercontent.com/8275168/32759362-0c6f7df8-c924-11e7-9133-bb7e827ba291.png">

**Comment by daubas** [comment]
餐飲已定
中餐：[麥斯盒子](https://www.facebook.com/pg/ComfortaBox/shop/?rid=1667452780161159&rt=6) 150人*100元
飲料：[飛蘭士](https://www.fresh-line.com.tw) 紅/綠茶/熱咖啡 三大桶

**Comment by yurenju** [comment]
@daubas 謝謝你 ^^ 我先把前兩項打勾，如果跟實際的情況有不同再麻煩你做修改~

**Comment by RobinHung** [comment]
飲料的部分不知道是否需要兩批? 分別是上午跟下午的tea break供應

**Comment by hwwhww** [comment]
午餐我有點顧慮，看起來我們應該沒有類似「休息室」的空間可以使用

1. 放講者在會場那吃便當可能會吃得有點苦（沒有桌子、觀眾會來干擾），所以是不是還是我另外找講者午餐地點比較合宜？
2. 150  人應該會有人得要坐在地上吃了

**Comment by RobinHung** [comment]
good point!

似乎需要找個場地來讓講者用餐，但除了講者之外，跟講者一同出席的來賓是否需要一起另外找場地用餐? (目前講者+來賓就已經19人了，要找場地可能會有點困難XD)

**Comment by daubas** [comment]
回應一下：
1.廠商的說法是飲料早到晚一整天沒問題，兩趟要多算一次運輸車錢就是。
2.午餐時間一般會眾不會在座位乖乖的吃，而會到處找場地吃（也許是大門口外面）。
3.講者用餐其實等同於設置講者休息室，目前看來沒有空間，可能得借用未來產房沙發區？

**Comment by hwwhww** [comment]
> 飲料：飛蘭士 紅 / 綠茶 / 熱咖啡 三大桶

@daubas 
提醒一下，希望 綠茶 能是無糖的，感謝 🙇🏻

**Comment by juincc0** [comment]
講者休息室是必要的 但應該只需提供一間就夠
