### ISSUE TITLE
Badge 事宜

### ISSUE THREAD

**Issue by yurenju** [EtherTW/beyondblock_taipei_2017#23]
Badge 或掛牌將用於控制會眾與廠商等參與人數能不能進入演講場地，有幾件事情要確定。

- [ ] 報名完成後，要用什麼形式讓門神辨識這個人可以入場，有幾個參考的方式：(1) 掛牌 (2) 貼紙貼在身上 (3) 蓋章 (蓋章好像比較不容易讓門神確認)
- [ ] 確認上述工作後，開始製作掛牌、貼紙或任何需要事前準備的物品。

**Comment by BrianPHChen** [comment]
可以使用一次性的紙手環，像是演唱會或馬拉松在使用的，我請朋友幫忙詢問價格

**Comment by yurenju** [comment]
補上 slack 上的討論連結 https://ethertw.slack.com/archives/G7QBCLHMG/p1510629045000190

**Comment by BrianPHChen** [comment]
【購買現貨公版】同一圖案同一顔色  尺寸10"x 0.75"
100條-- 240元 / 500條--960元 / 1,000條(一盒)-- 1680元 /  含包裹郵資 含稅  以台幣現金匯入，即刻安排出貨隔天可達
◎ 存根式腕帶( 11英寸長) 或是  比較寬的(  1英寸寬 ) 每1,000條加210元
◎ 時尚雷射腕帶 每1,000條加420元

【私版  訂做   】 尺寸10"x 0.75"  一版到底不換色   1,000條  -- 3500元 /含稅 包裹 郵資 運費
◎ 存根式腕帶( 11英寸長) 或是  比較寬的(  1英寸寬 ) 每條加0.2元
 
不取消我司帶頭LOGO 版費2500元 由我方吸收  ( 要求帶頭空白 則印刷版費2500自付；帶頭也要印客戶資料 則收取印刷版 2500+帶頭銅刻版6,000元=8500元 版費 ；日後 不更動版面 以後仍然可使用 不再收費 )
 以現金匯入，即刻安排製作7工作天可達， 報價含關稅、貿易服務費、含運費，含稅

**Comment by BrianPHChen** [comment]
![_______________](https://user-images.githubusercontent.com/7158388/32771787-79586dc0-c8e9-11e7-9e72-fab70a9cf96a.JPG)

**Comment by BrianPHChen** [comment]
我們可以買單色，然後上面寫報名的人的名字，滿便宜的

**Comment by tailingchen** [comment]
可以訂做不同顏色, 用來區別參與者/講者/贊助商/媒體

**Comment by tailingchen** [comment]
根據討論的結果, 最後結論製作Badge當作出入場證明.
識別證掛帶進度Update:
1. 接洽廠商: [昶綺有限公司](https://www.changchis.com/tw/products/?method=listing&sid=211)
2. 掛帶類別: 1公分走馬帶(黑色)+轉動S勾
3. 數量: 150
4. 價格: 
```
單價: 5/條 (未稅)
運費: 100元
總金額: 5*150+100=850
含稅: 850*1.05=893(開統一編號)
```
5. 付款進度: 已匯款, 預計11/21到貨

![ly-801](https://user-images.githubusercontent.com/18319268/32935595-79a2f6ca-cb36-11e7-8fe8-0a374c973dec.jpg)

**Comment by tailingchen** [comment]
識別證影印進度Update:
1. 雪柔象牙紙230磅(參考附件影像), A4: 4元/張, 彩色印刷每張加7元, 共11元/張 (未稅)
2. 裁切費用: 100元
3. 預計製作200張識別證, A4可印4張識別證, 金額預估約 (200 / 4) * 11 + 100 = 650 (未稅)
4. 識別證圖稿: 預計11/20前確認

![img_2908](https://user-images.githubusercontent.com/18319268/32935977-01f79520-cb38-11e7-9ac2-fff69361a417.JPG)

**Comment by tailingchen** [comment]
進度update:
1. 已收到識別證帶
2. 識別證已完成印刷且裁切
