### ISSUE TITLE
器材

### ISSUE THREAD

**Issue by yurenju** [EtherTW/beyondblock_taipei_2017#24]
目前贊助商的區域沒有任何的插座，需要延長線從會場牽到外面，並且提供每個廠商約兩個插座，這樣應該不至於過載。這個 issue 需要：

- [x] 確認贊助商的數量
- [ ] 依照上面的資訊加上再去了解一下場地最近的插座，評估需要多少延長線
- [ ] 準備這些延長線並且於當天帶去

**Comment by juincc0** [comment]
5(攤位數) + 1(relay) + 2(backup) = 8
接下來就看怎麼湊到這個數量
能幫忙帶的在下面回覆一下數量？

**Comment by yurenju** [comment]
如果贊助商數量確定是五個了，我就先把第一項工作打勾了

**Comment by yurenju** [comment]
至於距離外面攤位最近的插座讓我來問一下 Futureward

**Comment by yurenju** [comment]
Stephanie 回覆最近插座如下圖打 X 處

![function room](https://user-images.githubusercontent.com/22155/32768895-af8839d2-c954-11e7-9b61-ccb0b7b1c10f.png)

**Comment by hwwhww** [comment]
借這篇請問一下，投影機接電腦的線材是 HDMI 還是 VGA？或都有？
我可以帶 `Type-C 轉 HDMI` 的線
若是 VGA，`Type-C 轉 VGA` 的線可請線材大師 @changwu-tw 準備嗎？

**Comment by juincc0** [comment]
器材單
能幫忙帶的幫忙填在這裡
https://docs.google.com/document/d/1FvM-ZixwIyd3W_ZNkxBJ6WtUxu-Z8aY22HBNL_sDppo/edit
