### ISSUE TITLE
主持

### ISSUE THREAD

**Issue by yurenju** [EtherTW/beyondblock_taipei_2017#25]
主持人相關的工作目前有：

- [ ] 確認主持人的工作有那些
- [ ] 尋找到適合的主持人並且建立聯絡方式
- [ ] 當天聯絡主持人

**Comment by juincc0** [comment]
已詢問耀中，這兩天會有結果

**Comment by yurenju** [comment]
@juinc 如果有什麼新進展再麻煩你更新到這個 issue 來，感恩！

**Comment by hwwhww** [comment]
確認主持人的工作有那些
* 準備介紹詞
* 提醒講者演講時間剩幾分鐘，用愛與關切的眼神請他講快一點

**Comment by juincc0** [comment]
主持事宜由 @yaochunghu 協助

**Comment by yaochunghu** [comment]
主持事宜以確認

**Comment by RobinHung** [comment]
贊助廠商短講時間 參考#32
