### ISSUE TITLE
場控組事務

### ISSUE THREAD

**Issue by yurenju** [EtherTW/beyondblock_taipei_2017#26]
場控組是當天事務較多，目前已知的場控組事務：

1. 報到
2. 午餐便當（餐飲葷素）
3. 參加者管制（初步討論以報到時發貼紙作為參加者識別）

有一些事前籌畫可以先處理的：

- [ ] 確認場控組的事務除了上述三點還有沒有其他的
- [ ] 確定場控組的人員有誰，並且讓他們知道場控組的事務範圍

**Comment by juincc0** [comment]
我們可能會需要先弄一份細流

**Comment by yurenju** [comment]
@daubas 剛跟 @juinc  確認過場控這邊會由你負責，我先把這個 issue assign 給你，不過你身上還掛了不少工作，如果你需要幫忙的話可以到 slack 上跟大家說一下，可以分散一下工作量。

**Comment by daubas** [comment]
已經詢問場地會議室狀況，
會議室有四間，
費用都一樣是第一小時800元+第二小時後600元/小時。
第一第二間都是七人空間含一桌七椅，
第三間是十人空間含一桌十椅，
第四間是十人空間無桌椅。
11/25尚無預定。

我想可以直接借第三間整天？

**Comment by yurenju** [comment]
這邊我會去跟未來產房借這間會議室。
