### ISSUE TITLE
晚宴工作

### ISSUE THREAD

**Issue by yurenju** [EtherTW/beyondblock_taipei_2017#27]
晚宴工作有：

- [ ] 跟 @juinc 確認晚宴的動線安排
- [x] 尋找晚宴廠商
- [ ] 當天需要與晚宴廠商聯繫

**Comment by daubas** [comment]
- [x] 尋找晚宴廠商
目前已經找好晚宴廠商並且交付訂金，
不過還需確認送餐時間。

**Comment by yurenju** [comment]
@daubas 這個項目目前是你在幫忙的嗎？如果是的話想要先 assign 給你 :D

**Comment by daubas** [comment]
沒問題～

**Comment by yurenju** [comment]
感謝 m(_  _)m

**Comment by juincc0** [comment]
上回場勘時有稍微與 @yurenju 討論晚宴動線
1. 議程結束後於大廳大合照，順便淨空會場(需提醒會眾帶走隨身物品)，進行晚宴佈置
2. 佈置過程中控管會場進出人員，以防一般會眾混入
3. 佈置完成後，由場務組引導 講者/媒體/贊助/工作人員 進入會場

**Comment by hwwhww** [comment]
請教 @daubas 關於菜單
「只吃肉的人」能吃飽嗎？😳

**Comment by hwwhww** [comment]
我找不到 tea break 討論應該在哪一篇 issue，應該是有點心？
所以在這提醒一下，關於所有餐飲
有一位講者 `Cannot eat peanut`，所以能否請廠商標示一下若有 peanut 的食物？謝謝。

**Comment by daubas** [comment]
比較特殊的飲食需求可能要有人負責特別去處理，
也許是接待組？
目前都沒有定點心喔、主要是考慮現場放不下，
@hwwhww 覺得講者會需要點心嗎？
花生的部分我想中餐可以避免，
但晚餐要特別標可能廠商幫不上忙、
就也需要有人處理了，
菜單請見附檔。
[1125外來房產_外燴王880法式菜單.pdf](https://github.com/EtherTW/beyondblock_taipei_2017/files/1479680/1125._.880.pdf)

**Comment by hwwhww** [comment]
嗯嗯，我沒有覺得會需要有點心，只是一開始看 "tea break" 名字以為有，但沒有也 ok 的～
感謝提供資訊！
