### ISSUE TITLE
訪問區設立工作

### ISSUE THREAD

**Issue by yurenju** [EtherTW/beyondblock_taipei_2017#28]
請在這邊補上這個工作需要有什麼工作事項需要處理，我先猜測大概會需要的工作是：

- [ ] 設計採訪區背板
- [ ] 輸出採訪區背板，並事先保存
- [ ] 當天運送背板到場地

我感覺這個可能不是必備的項目，不過沒有參與到討論不是很確定。

**Comment by juincc0** [comment]
對於背板大小我沒啥概念， @ChihChengLiang 這個你有經驗嗎？
需要另外的工具來架設嗎？

**Comment by charlieworld** [comment]
訪問區的設立，需要考慮：

1. 動線
    為避免阻塞，通常都會設立在場外的某個牆邊。但我那天場刊印象中外面攤販會擺滿。
    不然就是直接在舞台最前方，投影幕那邊設立。
    活動結束後，可以直接把投影幕升起來，直接露出後面的背板（背景），也可以當成是合照的區域。

2. 光線
    如果要做的比較好，建議要考慮到訪問區的燈光是否昏暗，尤其是臉部的光線。 最好另外架設一個燈，這個部分我可以去借借看。 ( 重要等級為 nice to have)

3. 背景
    通常背板會有幾種，一種是巨大珍珠板輸出的，不容易搬運，容易折到。

    另外一種可以像是「[易拉寶](https://www.google.com.tw/search?q=%E6%98%93%E6%8B%89%E5%AF%B6&safe=off&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiU8IG_lr3XAhWFNJQKHdA9CMsQ_AUICigB&biw=1187&bih=897&dpr=1)」，我在沃草的經驗是可以用大概三個拼成一個背景。

   通常來說背板都是辦一次活動就丟掉，我覺得滿可惜的，所以可以考慮「背板模組化」。
   像這樣：[https://imgur.com/a/RnNIp](https://imgur.com/a/RnNIp)
    
   最大的背景（不管是用珍珠板還是易拉寶），就是單純的背景設計， 標語、Logo 等等可以彩色輸出後，
   貼在厚的珍珠板，再用雙面膠貼在背景上，這樣之後的場次就可以抽換這些元素

   以上是一點心得給各位參考

**Comment by BrianPHChen** [comment]
其實我們公司有打算做這些事情，我來問問看有沒有什麼方式合作

**Comment by willliw** [comment]
我以為可能在沙發那邊聊聊就好。攝影大哥自己喬角度這樣，從簡就好？

**Comment by BrianPHChen** [comment]
不然就沙發區聊聊好了，感覺做背板又要把所有廠商弄近來，挺麻煩的，我請攝影大哥幫忙拍

**Comment by yurenju** [comment]
如果大家決定要在沙發區聊聊，那這個 issue 就關囉！如果你認為還是有設置採訪區的必要，請 re-open 這個 issue，感謝大家！
