### ISSUE TITLE
行前通知（給合作單位）

### ISSUE THREAD

**Issue by daubas** [EtherTW/beyondblock_taipei_2017#29]
我們應該要準備一份行前通知，
分別給會眾跟合作單位，
初步設想了一下，
內容要包括：

1. 會眾
- 交通建議
- 停車場位置／價格
- 聯絡人

2. 廠商
- 進出場時間
- 廠商短講時間與順序

3. 講者
- 有晚宴的存在（仍無法保證出席率）
- 休息室（#6 (comment) 討論中）
- 當天流程
- 投影片是否可以提早提供（但我想大多數講者會是當天才提供）

大家有想到歡迎補上。

Update: Yuren 11/17 更新講者部分

考慮要加進去的內容：
- 吸菸區

**Comment by yurenju** [comment]
這個 issue 我先拿下了，主要會進行的工作是整理 @daubas 提到的資訊，如果大家覺得還有什麼需要在會前通知的請留言在這邊。

另外目前我預計在 11/23 發布行前通知，到時候可能會需要 @juinc 透過 kktix 的系統幫忙發送給會眾，到時候會提供給你通知內容。

**Comment by hwwhww** [comment]
請問會有講者版的嗎？
提醒他們
* 有晚宴的存在（仍無法保證出席率）
* 休息室（https://github.com/EtherTW/beyondblock_taipei_2017/issues/6#issuecomment-344988165 討論中）
* 當天流程
* 投影片是否可以提早提供（但我想大多數講者會是當天才提供）

**Comment by daubas** [comment]
講者我覺得是給接待組告訴他們議程並跟著，
畢竟現場會有什麼需要可能要隨機應變；
投影片也要提早去測試機器，
每位講者的時間都很不多、務必把裝投影片的時間盡量縮短；
這部分可能在行前會討論吧

**Comment by yurenju** [comment]
@daubas 覺得可以行前通知 + 接待組兩者並行，像是講者晚宴還是要先行告知，不然他安排了晚餐就不會出席了。

**Comment by ChihChengLiang** [comment]
看到行前通知又剛好看到這張 XD 
![image](https://user-images.githubusercontent.com/3391420/32928842-b6f5dfaa-cb19-11e7-9b10-3b0a92f084a4.png)
[出處](https://www.facebook.com/flying.crazyer/photos/a.1769014240020348.1073741829.1767237020198070/1955652914689812/?type=3&theater)

**Comment by yurenju** [comment]
抖抖 der，大家要發大量信前一定要好好想想 `傅斯年 (沒說這句)` XDDD

**Comment by RobinHung** [comment]
贊助商短講時間 參考#32

**Comment by yurenju** [comment]
## 會眾行前通知

各位與會者您好，感謝您參與 BeyondBlock Taipei 2017，研討會即將在這個禮拜六舉行了！這邊有幾點提醒事項請大家特別注意：

### 時間地點

本次研討會為 11/25 週六早上九點開始報到，九點半活動正式開始，地點於「未來產房．南京復興」，地址為 105 台北市松山區長春路 343 號地下一樓，距離南京復興捷運站步行約五分鐘的路程即可抵達。

另外本周天氣可能會降雨，也別忘了攜帶雨具！

### 線上討論

請加入 Taipei Ethereum Meetup 的 slack，當天我們可以於線上討論議程： http://bit.ly­/252hNY0 通關密語為 decentralized。我們也建立了一個線上共筆頁面讓大家可以共同編輯對於講題的筆記：

https://hackmd.io/c/r1z7g7kxM

### 電源

由於場地的電源插座數量有限，請充飽您的電腦再來參加活動喔！另外若您有延長線當天也可以攜帶至會場讓更多人可以使用電源！

### 社群媒體標籤

本次活動採用的 hashtag 為 #BeyondBlockTaipei 歡迎大家分享照片與貼文時使用！

### 其他

如果您有遇到任何疑問，可以詢問當場的工作人員，也可以傳訊至 Taipei Ethereum Meetup 的粉絲團，我們會有工作人員協助回訊。

https://www.facebook.com/eth.taipei/

**Comment by yurenju** [comment]
我對贊助廠商與講者的資訊不是說很齊全，不知道 @daubas 可否幫忙寫贊助廠商的行前通知， @RobinHung 幫忙寫講者的行前通知呢？感恩 m(_  _)m

**Comment by yurenju** [comment]
講者的行前不要忘了加上：目前借用的會議室是不可飲食的，而在中午未來產房可以提供他們的廚房區供講者用餐，時間為一個小時，正好是我們目前安排的用餐時間的長度。

原文：
```
朱先生您好，

我們合約後面第8條有註明會議室是禁止飲食。
我們週六可以免費提供廚房給你們用餐。
用餐時間為1小時。

因為我們這裡是辦公空間，所以除了會議室、廚房其他空間要請你提醒貴賓不能亂走。
謝謝。
```

![default](https://user-images.githubusercontent.com/22155/33015930-8dcbb8a0-ce27-11e7-9636-320500d4de3c.png)

**Comment by yurenju** [comment]
### 講者行前通知的一些提醒

* 給講者的行前通知需要自行攜帶電腦，也有可能會需要準備 adapter。
* 現場投影機是 HDMI，不支援 d-sub
* 如果要使用公用電腦播放投影片，需要準備 PDF 格式

1. Format of presentation (PPT, PDF):
2. What audio/video does your presentation include, if any: 
3. Do you want to plug in your laptop for your presentation?
If yes, what video outputs does your laptop support (HDMI, Mini Displayport):

**Comment by changwu-tw** [comment]
我覺得這兩次宣傳可以加上贊助商的簡介，感謝一下

**Comment by RobinHung** [comment]
### 講者行前提醒
* The projector at the venue is HDMI port. If you’re going to use the PC provided by us, please export the slide to PDF format.
* The venue locates at FutureWard - Central. (Address: B1F., No.343, Changchun Rd., Songshan Dist., Taipei City, Taiwan.)
* The conference starts at 9:30 AM.
* After the conference, We’ll have the buffet dinner at the venue!
* For more information, please visit our official website: ethertw.github.io/bbt2017

**可加入內容** (ref: @yurenju)
1. 場地地圖，標示用餐區以及會議室（這個我晚點給你，我還在跟未來產房確認我畫的地圖有沒有問題）
2. 用餐時間，因為只有用餐時間用餐區才開放使用

*請大家在幫忙看一下有什麼可以新增或修改的內容了，感謝!*

**Comment by yurenju** [comment]
我畫了一下示意圖，附這張圖或接待講者時需要說明一下，因為講者休息室以及講者用餐區都在辦公室區域，這兩個地方是需要辦公室的卡才能進去的。

<img width="2481" alt="futureward_central_floor_plan__aug_2017_new_" src="https://user-images.githubusercontent.com/22155/33079522-c74d8966-cf10-11e7-8998-5f513489aa98.png">

**Comment by yurenju** [comment]
@juinc 給會眾的行前通知應該沒問題了，請你在週五早上透過 kktix 系統發送給所有與會者。內容請參考 https://github.com/EtherTW/beyondblock_taipei_2017/issues/29#issuecomment-345525979

贊助商的行前通知應該會由 @daubas 發送對吧？如果內容不方便貼上來也不用貼在這裡。或許也是週五早上發送，不過你可以挑一個比較適合贊助商的時間。

我不太確定的是講者的行前通知要如何發送，可能要請 @RobinHung 跟其他議程接待或跟講師比較熟識的人協調一下發送的管道？我原本預想是透過 email，不過不太確定是否有建立講者通訊錄，另外週五早上可能也會太晚，畢竟許多人都要坐飛機來，或許講者的部分可以早一點發送？

**Comment by hwwhww** [comment]
要確保講者能看到，可以轉成 PDF 後我們在群裡通知～

**Comment by yurenju** [comment]
好喔，或許也可以寫在 google docs 裡面，然後傳 google docs 的連結，看你們怎樣比較方便！

**Comment by RobinHung** [comment]
講者行前通知(google doc): https://docs.google.com/document/d/1HXQONlbsAEPnBVpAoYurcRVlGPBs2ZTB5x7Dy267eNs/edit

如果沒有問題的話，就應該可以轉成PDF檔送出了

**Comment by yurenju** [comment]
這則等到三種行前通知都發了再關好了？明天等會眾的行前通知發了我再關

**Comment by juincc0** [comment]
已發信給會眾
