### ISSUE TITLE
各組負責人

### ISSUE THREAD

**Issue by juincc0** [EtherTW/beyondblock_taipei_2017#3]
ref: [第一次會議紀錄](https://docs.google.com/document/d/1Mt4FTayrPOGDcGZrT_hxILC7bWak_bbe1rVWPpLZZpA/edit)
## 分組
總召 @juinc
副召 @changwu-tw 

| 組別 | 負責人 | 內容 |
| :---: | :---: | :---: |
| 議程 | @robinhung | 議程、講者晚宴、交流活動 |
| 設計 | @ChihChengLiang @tailingchen @bichenkk | 衣服、貼紙 |
| 網站 | @BenjaminLu | 議程網站、Dapp |
| 行銷 | @yurenju | 包含線上與線下的宣傳，包含跟別人場地的宣傳 |
| 直播 | @charlieworld | 活動直播|
| 記錄 | @ChihChengLiang | 照相、給贊助商的照片|
| 贊助 | @daubas | 對外聯繫窗口 |
| 公關 | @willliw | 提供對媒體、學校跟政府的接口|
| 財務 | @daubas @willliw | 保管費用、記帳、會計 |
| 場務 | @daubas  | 場控 / 動線 / 訂便當 |

#### 請能夠認領工作的人在下面回覆

**Comment by quesalltime** [comment]
我是Ken,目前的安排我是幫忙直播,所以在記錄組(quesalltime那個是我的githubID)

**Comment by daubas** [comment]
會議紀錄已決定事項的部分不確定放那，
先放這邊好了：

11/10會議決定事項

- 出納、保留票、講者禮物 由 @willliw 處理
- 主持人 由 @juinc 處理
- 實作時段安排 由 @ChihChengLiang 處理

**Comment by yurenju** [comment]
雖然還有兩個 TBD，但是目前應該所有工作都上軌道了，先關掉這個 issue，如果大家覺得還有需要確認負責人請再 re-open 這個 issue
