### ISSUE TITLE
接待

### ISSUE THREAD

**Issue by juincc0** [EtherTW/beyondblock_taipei_2017#31]
| 講者 | 負責人 | 備註 |
| :---: | :---: | :---: |
| Vlad | @mhchia | |
| Karl | @mhchia | |
| Lane | @mhchia | |
| Thomas | @mhchia | |
| Ben | @hwwhww  | 會和許昕一起來 |
| Philipp | @hwwhww   | 會和許昕一起來 |
| Vitalik | @tailingchen  | AMIS 會有人幫忙接機 |
| Loi | @changwu-tw | |

- 當日接待細節

**Comment by hwwhww** [comment]
少列了 Ben 總，也是和許昕一起來

**Comment by BrianPHChen** [comment]
@hwwhww 你剛剛害邱駿問台灣班總為什麼要被接待

**Comment by hwwhww** [comment]
@mhchia 早上帶 Karl 去買星巴克

**Comment by mhchia** [comment]
OK
