### ISSUE TITLE
直播

### ISSUE THREAD

**Issue by charlieworld** [EtherTW/beyondblock_taipei_2017#33]
### 負責人
 - Charlie 查理 charlieworld2008@gmail.com
 - Jason yehchicken@gmail.com
 ### 場地器材
 現場網路有實體線路，會走實體線路， @charlieworld 會帶網路線
 - [x] DV 一台
 - [x] DV 腳架
 - [x] HDMI 擷取盒
 - [x] HDMI 30M 線
 - [x] 延長線

 ### 直播
分早上 (9:30 ~ 12:20) 與 下午  (13:30 ~ 17:20) 兩半場
 - [x] 上半場連結： https://youtu.be/md9iNDdAmVo
 - [x] 下半場連結： https://youtu.be/9RtSod8EXn4
 - [x] 上半場文案
 - [x] 下半場文案
 - [x] 播放清單連結： https://www.youtube.com/playlist?list=PLYqLIBg0y8JzD6Xoi_mnfssVbfjiw0tFa

 ### 直播素材
 - [x] 海報 (1920 X 1080 )

**Comment by ChihChengLiang** [comment]
@bichenkk 鏡面( 1920 X 1080 ) 要再麻煩你囉

- 上面需要贊助廠商 logo

**Comment by ghost** [comment]
海報 (1920 X 1080 ) 上要有
- beyond block logo
- 贊助廠商 logo
?

**Comment by charlieworld** [comment]
我覺得這張海報排版改成橫式 1920 x 1080 就很棒了　（資訊應該跟海報上的一樣就行？）

https://imgur.com/a/uaz2s

**Comment by ghost** [comment]
okay I send you tonight

**Comment by juincc0** [comment]
@bichenkk 
資訊都要有喔

**Comment by juincc0** [comment]
@charlieworld 
直撥這邊還缺什麼嗎

**Comment by charlieworld** [comment]
剩下直播畫面的排版布置而已，這部份我會處裡　:) 
其他都完成了

**Comment by juincc0** [comment]
ok，close
