### ISSUE TITLE
場控

### ISSUE THREAD

**Issue by daubas** [EtherTW/beyondblock_taipei_2017#34]
當天場控工作分配
https://docs.google.com/spreadsheets/d/1ELOQtbSuzNMkCSgjfWEBwEsuJvEL8csutsLZSEIPlis/edit#gid=0
歡迎大家認領唷

**Comment by mhchia** [comment]
我可以幫忙接待處，但早上要帶客人們來會場，不知道來不來得及。
另外想知道負責人需要做什麼事。
感謝～～
