### ISSUE TITLE
列出所有會使用休息室的人員

### ISSUE THREAD

**Issue by yurenju** [EtherTW/beyondblock_taipei_2017#35]
由於未來產房只能給我們二十張可以進入共用工作區的卡片而休息室在工作區內，並且不希望輪流換卡片進去，所以在這邊想要做個列表放所有會進入休息室的人，不知道可不可以請 @RobinHung 跟接待組的大家列一下呢？另外我會需要進去，所以先扣掉我一個人變成 19 張。

另外這邊列出所有人，大家可以從這邊篩選：

### 講者與貴賓
* Vitalik Buterin
* Vlad Zamfir
* Karl Floersch
* Virgil Griffith
* Nicolas Lin
* Lane Retting
* Jennifer Huang
* Sydney Lai
* 許昕
* 托婭(Toya)
* 何斌
* 单保龙
* 黃磊磊
* Philipp Seifert
* Jannik Luhn
* 石橋
* Loi Luu
* Thomas Greco
​
### 工作人員
* 梁智程 / Chih-Cheng Liang
* Ben
* Yuren Ju
* Ken
* Jerry
* 陳保羅
* Will
* 邱駿 / Juin Chiu
* Chang-Wu Chen
* 查理
* Jason
* Brian
* Hsiao-Wei Wang
* 洪友謙 Robin
* Kevin 脈瑄
* Nicolas Lin
* KK Chen
* Tai-Ling Chen
* 小馬
* 黃雅信 / Yahsin Huang​

**Comment by hwwhww** [comment]
`不希望輪流換卡片進去` - 是也不能由有卡片的人帶人進去嗎？

**Comment by yurenju** [comment]
沒錯，要有卡片才可以進去。

**Comment by hwwhww** [comment]
這麼嚴格的話喔～

### S 保護區

1. Vitalik Buterin
2. Vlad Zamfir
3. Karl Floersch
4. Lane Retting
5. 何斌
6. Loi Luu
7. Thomas Greco
8. Philipp Seifert

### A 保護區

1. Virgil Griffith
2. Jannik Luhn
3. 許昕
4. 托婭 (Toya)
5. 单保龙
6. 黃磊磊
7. 石橋

### B 保護區

1. Jennifer Huang
2. Sydney Lai

---

B 的可以不用進去，
A 的主要考量是他們會想一起吃便當....?

**Comment by RobinHung** [comment]
### 門禁卡分配
* 講者 x8
* 接待 x4
* Staff x8

**Comment by yurenju** [comment]
這個 issue 這樣應該是完成了 close it!
