### ISSUE TITLE
網站

### ISSUE THREAD

**Issue by BenjaminLu** [EtherTW/beyondblock_taipei_2017#4]
議程網站目前規劃是以下幾個頁面，需要RWD，支援中英兩個語系
[報名網站repo](https://github.com/EtherTW/confweb2017)

1. 首頁landing page: conf標題和KKTIX報名連結
2. 關於頁面: 講述此會議的精神
3. 最新消息: 連結Taipei Ethereum Meetup社團消息
4. 講者: 介紹講者
5. 議程: 議程題目和時間表
6. 交通路線
7. 贊助廠商

空間暫定放github pages，domain已經買好
覺得有屬於區塊鏈領域該有的特殊頁面可以回覆討論
心有餘力有Dapp想法的也可以這邊討論，如果想法很多再另外開一個issue
與設計師配合初版出來我再開個repo

議程參考 #6

**Comment by RobinHung** [comment]
#### 以下是我看到關於網站的一些問題
* 在原本關於“最新消息"的欄位裡，提到的是**社團**，但是連結給的是**粉絲專頁**。
    我假設是兩個連結都公開，所以有修改了文字說明，剩下的是需要多提供**社團**的連結

* 在"議程"裡，中英文轉換好像有問題 (更換語言後，還是會維持在系統的預設語言)

* 在"議程"裡，副標題的文字大小應該要略小一點，然後我建議把主標題改成**演講主題**，然後副標題則是**講者姓名** (我在其他conference的agenda看到都是這樣排版的)

* 我把交通資訊的英文欄位改成"Venue Location"後，排版會跑掉。看看有沒有辦法修改，如果沒有辦法的話，就改成"Venue"就好了

* 這場conference的名稱要叫做"BeyondBlock Taipei"還是"BeyondBlock Taipei 2017"可能需要統一一下，然後或許可以把網頁的背景圖片改成kktix的那張 (個人建議)

**Comment by ChihChengLiang** [comment]
Venue 其實比 Venue Location 好些，後者贅字。

**Comment by BenjaminLu** [comment]
議程語系切換的問題已經修正

**Comment by changwu-tw** [comment]
網頁更新
1. 會場資訊 (ref: RobinHung)
2. 贊助廠商的網頁連結
3. 選單加入贊助廠商

**Comment by yurenju** [comment]
網站目前已經上軌道了，如果還有什麼網站的大項工作需要放在 github 追蹤，請再另外開 issue。
