### ISSUE TITLE
媒體  press kit  (11/3)

### ISSUE THREAD

**Issue by ChihChengLiang** [EtherTW/beyondblock_taipei_2017#5]
我建議仿遊戲公司的方式，直接製作一個 press kit 給其他媒體使用。我們寫好基本事實，媒體可直接照上面素材撰稿

有現成工具可以使用 http://dopresskit.com/

範例： http://redcandlegames.com/presskit/sheet.php?p=detention&l=ch

**Comment by ChihChengLiang** [comment]
我可以做一份初版

**Comment by ChihChengLiang** [comment]
php 苦手。Press kit 用 hackmd 代替 https://hackmd.io/MYRgZgbCAmwJwFpoFMYICwgKzAQIwHYsQEAGKAQ1LDjxgryA

**Comment by yurenju** [comment]
這個工作項目看起來已經有基礎的資訊了， @ChihChengLiang  覺得還有什麼需要加的，還是有需要什麼其他的協助嗎？

**Comment by hwwhww** [comment]
@bichenkk 做的海報設計與相關素材要不要也放進去？

**Comment by ChihChengLiang** [comment]
好主意，我收一下。剩下的等媒體問，我們再給吧

**Comment by ChihChengLiang** [comment]
need:  
1. 新聞稿：通常都會先發一個新聞稿當主體，也會跟記者指這次活動的亮點出來，然後再依到場後的收獲心得改寫原來的新聞稿。
2. 亮點的影片（在YouTube上）
3. 大大講者/現場論壇狀況的照片2-3張
