### ISSUE TITLE
議程

### ISSUE THREAD

**Issue by juincc0** [EtherTW/beyondblock_taipei_2017#6]
## 議程 (Version 2)
| 時間 | 內容 |
| :---: | :---: |
| 0800-0900 | 場佈 |
| 0900-0930 | Registration |
| 0930-0940 | Opening |
| 0940-1010 | Lane Rettig (Founder of CryptoNYC): Blockchain in NYC
| 1010-1110 | Karl Floersch (Ethereum Researcher): Smart Contract Tutorial
| 1110-1130 | 休息 |
| 1130-1200 | 何斌 Ben (CEO of ImToken): ImToken 2.0 |
| 1200-1330 | 午餐 (自理) |
| 1330-1400 | Raiden Network: Trustlines Network |
| 1400-1430 | Loi Luu (CEO of Kyber Networks): Kyber Networks |
| 1430-1500 | 工商時間 |
| 1500-1530 | 休息 |
| 1530-1600 | Vlad Zamfir (Ethereum Research Lead): Blockchain Governance |
| 1600-1630 | Vitalik Buterin (Creator of Ethereum): Ethereum 2.0 |
| 1630-1650 | Q&A |
| 1650-1700 | 拍照合影 |
| 1700-1900 | 晚宴 |
| 1900-2000 | 場地還原+清潔 |

## 講者
- Foundation Creator: [Vitalik Buterin](https://www.crunchbase.com/person/vitalik-buterin)
- Foundation Researcher: [Karl Floersch](https://www.linkedin.com/in/karlfloersch/)
- ImToken CEO: [何斌](https://medium.com/taipei-ethereum-meetup/%E6%93%81%E6%9C%89%E7%B6%B2%E8%B7%AF%E7%AC%AC%E5%9B%9B%E5%A4%A7%E7%A4%A6%E6%B1%A0-ethfans-%E4%B8%AD%E5%9C%8B%E4%BB%A5%E5%A4%AA%E5%9D%8A%E7%A4%BE%E7%BE%A4%E9%80%99%E6%A8%A3%E7%B6%93%E7%87%9F%E7%94%9F%E6%85%8B%E7%B3%BB-f659573c555f)
- Kyber Networks CEO: [Loi Luu](https://www.comp.nus.edu.sg/~loiluu/)
- Founder of CryptoNYC: [Lane Rettig](https://www.linkedin.com/in/lanerettig/)
- Taiwan's speaker (TBD)

Note:
1. Vitalik 壓軸，原因：下午飛抵台灣

**Comment by yurenju** [comment]
這邊節錄我跟 @juinc 在 #7 對於議程的討論，因為討論的話題大多在議程相關，所以移到這邊來。

@yurenju
> [off topic] 如果要增加互動，除了場地以外，也可以思考一下怎麼從議程安排。比如說安排一些以討論為基礎的議程。這在台灣的研討會比較少見，不過我在國外參加的 Web Summit 跟 Code for America 都有遇過，主持人基本上是提出一些問題，並且用一些機制帶領大家討論。比如說分四個群組，然後四個工作人員協助這四個群組一起想出一些意見，接下來在一起提出這些意見跟不同的群組之間討論。
>
> 不過這完全離題了 XDD
>
> 回到正題，我們可以在場地上選擇比較容易增進討論的場地，不過我也想多了解一下除了 @juinc 提出的選場地的想法外，大家還有什麼想法覺得怎樣的場地形式可以增進討論。除了場地的選擇外，也可以從場地布置下手。

@juinc 
> 小朱上面提出的想法比較類似 workshop，但這種做法其實風險很高，主要考量兩點：
>
> 1. 我們不知道台灣 blockchain 社群的成熟程度 (或者可以說：不成熟)
> 2. 我們不知道講者的互動程度
> 所以安排workshop的結果有可能會很乾
> 
> 我覺得保險牌是把tea break拉長，餐點好一點，場地好一點 (例如有不錯的景觀裝置或者沙發區)，讓大家感到愉悅放鬆，讓講者跟聽眾自由互動，或許會激發出不同的效果，我們也可以於事後徵詢講者的建議，也試探台灣的社群成熟度，有助下一次設計出更好的議程
> 
> 但我相信某個程度的帶領是必要的，但可能不用到議程的形式

**Comment by RobinHung** [comment]
暫定議程
---------
* 08:30 - 09:30 工作人員進場場佈

* 09:30 - 10:00 報到
* 10:00 - 10:30 EtherTW開場 + 來賓合影... (Vitalik會缺席)
* 10:30 - 11:10 Slot 1
* 11:10 - 11:50 Slot 2
* **11:50 - 13:30 LUNCH TIME**
* 13:30 - 14:10 Slot 3
* 14:10 - 14:50 Slot 4
* 14:50 - 15:20 贊助商 工商時間
* **15:20 - 15:50 TEA BREAK**
* 15:50 - 16:30 Slot 5
* 16:30 - 17:10 Slot 6
* **17:10 - 19:00 晚宴**
* 19:00 - 20:00 場地還原+清潔(20:00撤場)

**Comment by RobinHung** [comment]
議程 (final version)
---------
* 08:00 - 09:00 工作人員進場場佈

* 09:00 - 09:30 Registration
* 09:30 - 09:40 Opening by EtherTW
* **09:40 - 10:10 Lane Rettig (Founder of CryptoNYC - Blockchain in NYC)**
* **10:10 - 11:10 Karl Floersch (Ethereum Researcher - Smart Contract Tutorial)**
* 11:10 - 11:30 BREAK
* **11:30 - 12:00 何斌 Ben (CEO of ImToken - ImToken 2.0)**
* 12:00 - 12:20 Our Sponsors
* 12:20 - 13:30 LUNCH TIME (自理)
* **13:30 - 14:00 Raiden Networks (Trustlines Network)**
* **14:00 - 14:30 Loi Luu (CEO of Kyber Networks - Kyber Networks)**
* 14:30 - 15:00 工商時間
* 15:00 - 15:30 BREAK
* **15:30 - 16:00 Thomas Greco (The Value of Open Financial Networks)**
* **16:00 - 16:30 Vlad Zamfir (Ethereum Research Lead - Blockchain Governance)**
* **16:30 - 17:00 Vitalik Buterin (Creator of Ethereum - Ethereum 2.0)**
* 17:00 - 17:20 Q&A
* 17:20 - 17:30 拍照合影
* 17:30 - 20:00 晚宴
* 20:00 - 21:00 場地還原+清潔(21:00撤場)

**Comment by changwu-tw** [comment]
建議:
1. Vlad 與 Loi 交換一下時間
2. 多一個講者與觀眾交流的時間在 16:30- 
(彈性時間, 若乾掉就趕緊結束, 問題可以提早在網上搜集 ex: 你最想跟 V 說的話)

**Comment by juincc0** [comment]
補充一點：
這次議程應該就是全英文吧？

**Comment by RobinHung** [comment]
除了imToken的王斌以外，其他都是英文

**Comment by juincc0** [comment]
有辦法請王斌用英文發表嗎

**Comment by RobinHung** [comment]
這個就要請 @changwu-tw 去詢問了

**Comment by BenjaminLu** [comment]
我是建議告知講者聽眾有非中文語系國家的人，讓講者自己去決定要用什麼語言來進行議程就好
如果他們認為用英文效果會比較好，自然就會改用英文講了

**Comment by BenjaminLu** [comment]
麻煩請給中英文版議程各一份，方便網站更新

**Comment by yurenju** [comment]
講者接待應該要在這邊討論，上次場勘時有提到這項工作，不過似乎不是很明朗。

**Comment by juincc0** [comment]
@ChihChengLiang 分組名單出來後就能開始著手了

**Comment by yurenju** [comment]
@RobinHung 想請你把議程目前還有的工作項目列出來，比較明確的知道還有什麼工作需要進行的，謝謝 :D

**Comment by RobinHung** [comment]
1. 關於講者接待的部分，目前似乎還不是很清楚，或許等到行前會的時候再直接討論?!
2. 我在想Karl的smart contract tutorial的部分，不知道有沒有辦法請Karl事先提供教學的內容，一來是讓工作人員先熟悉內容之後，比較好去解決觀眾的問題，會讓場面比較不亂，二來是在conference前，可以先提供環境設置的教學(理想上)，讓當天至少不用再花時間去解決這些比較基本的問題。
3. 當天會是統一使用一台電腦來播放投影片吧?! 需要自備電腦還是場地會提供?
4. 最新的議程是在官網上，這個issue裡的議程要麻煩 @juinc 再去修正了

另外關於宣傳和餐飲的問題，我就再留言到各自的issue裡好了

**Comment by RobinHung** [comment]
補充: 當天的開場應該是要稍微介紹一下Taipei Ethereum這個社群，這個重責大任事就交給 @ChihChengLiang 了嗎XD

**Comment by hwwhww** [comment]
> 我在想 Karl 的 smart contract tutorial 的部分，不知道有沒有辦法請 Karl 事先提供教學的內容，一來是讓工作人員先熟悉內容之後，比較好去解決觀眾的問題，會讓場面比較不亂，二來是在 conference 前，可以先提供環境設置的教學 (理想上)，讓當天至少不用再花時間去解決這些比較基本的問題。

我可以負責問 Karl

**Comment by hwwhww** [comment]
> 關於講者接待的部分，目前似乎還不是很清楚，或許等到行前會的時候再直接討論?!

若是會議開始前的接待
  1. Vlad、Karl、Lane、Thomas在我們的掌控（？）下， @mhchia 會帶他們來
  2. Philipp & Ben 會和許昕一起來，我們也是能聯絡的到
  3. Vitalik 由 AMIS 的人負責當天帶來
  4. 請問 Loi 的聯絡人是哪位？

會議當天的接待，好像還沒討論過

**Comment by RobinHung** [comment]
還有一個是贊助廠商短講的部分：在上午(12:00 - 12:20)有兩場，下午(14:30 - 15:00)有三場，順序的部分看看廠商部份有沒有特殊的需求(要麻煩 @daubas 詢問了，感謝!)

如果沒有的話就我直接排定了

**Comment by RobinHung** [comment]
> 請問 Loi 的聯絡人是哪位？

目前似乎還沒有人認領
> 會議當天的接待，好像還沒討論過

可能需要決定一下當天講者的集合時間，需不需要有人帶他們來會場(不過我想人力可能會不太夠，如果住的旅館很分散的話)，應該要把他們的時間跟觀眾的進場報到時間錯開
或許可以幫講者準備很台灣式的早餐...冰奶茶(?)

**Comment by daubas** [comment]
補個資訊，找到產房平面圖，好像有四間meeting room，當天看要不要直接整間借下來做講者休息室跟工作人員置物區  
![futureward central floor plan aug 2017 new](https://user-images.githubusercontent.com/6070892/32904496-6b9308ee-cb32-11e7-884f-4d1888a50d1f.png)

**Comment by yurenju** [comment]
如果決定了要借休息室盡早跟我說喔！

**Comment by changwu-tw** [comment]
Loi 由我來幫忙接待

**Comment by juincc0** [comment]
@yurenju 目前暫定借一間會議室
用途：1. 午餐 2. 休息 3. 準備

**Comment by hwwhww** [comment]
請先確認會議室桌椅數量

**Comment by daubas** [comment]
目前會議室需求是？
會讓所以講者一同午餐的話，
講者八人+接待組應該會是16人左右的需求？
可能麻煩 @yurenju 確認一下meeting room的桌椅與價錢，
看看夠不夠用。

**Comment by hwwhww** [comment]
1. 覺得不要讓 VIP 也在外面吃
2. 會議室內 staff 2人 控場就好？

**Comment by juincc0** [comment]
相關討論移至 #31

**Comment by hwwhww** [comment]
>  Karl 的 smart contract tutorial 的部分，不知道有沒有辦法請 Karl 事先提供教學的內容

Karl: I'll send tonight or tomorrow

**Comment by hwwhww** [comment]
Karl: Also so most of my tutorial will be based on my part 1 and 2 of learning Solidity at karl.tech

* https://karl.tech/learning-solidity-part-1-deploy-a-contract/
* https://karl.tech/learning-solidity-part-2-voting/
