### ISSUE TITLE
場地 Survey

### ISSUE THREAD

**Issue by yurenju** [EtherTW/beyondblock_taipei_2017#7]
先問一下之前有辦過活動的朋友找 100 人的場地，並且進行場勘看看是否符合我們的需求。目前我們的需求如下：

## 需求
* 100 人的場地
* 單軌議程
* 有接待處的空間
* 提供 100 人不會堵塞的網路，可以問問以前有辦過怎樣類型的活動，當時網路狀況如何（需計算每人可能至少有兩個上網裝置如電腦、手機）
* 提供適量電源插座，20 ~ 30 個插孔應該足夠。
* 旁邊有空間讓廠商擺攤，提供桌椅（不確定）

## 候選場地

|場地名稱|大小|接待處空間|網路狀況|電源插座|擺攤空間|費用|
|----------|----|-------------|---------|---------|--------|----|
|微軟|大|Y, 於 1F, 場地於 19F |可申請|充足|不可擺攤|免費，須提供一個session|
|未來產房|可 120 人，但會稍擠|有|據稱良好|前後約十個，需要延長線|有|假日三小時一萬|
|CLBC|TBD|TBD|TBD|TBD|TBD|免費，由 CSS 公司提供|
|Mozilla|太小|無|良好|多|沒問，但可能無法擺攤|無|
|CDIB |適中，人再多就要用站的|Y|無，有可能需要自行架設|少|無|免費，由 AMIS 提供|

### 微軟場地
由 @ChihChengLiang 協助詢問
場地費用：由微軟贊助
場地：台灣微軟會議室Conf Room CLS MPR 1-3
(微軟 19 樓會議室 + Social area + 申請1樓報到處 + 冷氣空調)

由於國泰世華大樓的安全控管，因此承租用戶，需要以下配合事項
* 請提供活動網址、Agenda
* 請提供至少三位工作人員，在1樓做報到，幫忙刷卡帶學員上樓，還有在19樓按下開門的動作。
* 報到時間：11月25日星期六 XX :00-XX:XX
* 報到地點：台北市信義區忠孝東路五段68號1樓
* 活動地點：台灣微軟會議室Conf Room CLS MPR 1-3  (台北市信義區忠孝東路五段68號19樓)
* 提供與會人員名單，需於11月13日前提供與會名單，包括：英文姓名 + 中文姓名。微軟需要印製訪客貼紙，警衛看到才會放行
* 訂餐：如有飲食需求，請至 Break out area 享用
* 還原場地
  * 清潔阿姨週末不上班，要靠自己
  * 裝過食物的包裝要拿到公區垃圾桶, 而非放在 Social area
  * 請告知大約需要多少垃圾袋
  * 需要工作人員還原場地，若因食物造成地毯污漬，微軟RE&F將對活動單位收取清潔費大約５萬元（洗地毯費用）
* 提供一場 20 分鐘演講：微軟將會提供一場 20 分鐘演講，講者會是 Azure 經理

### 集思台大會議中心
費用：18,000 / 4hr 

### CLBC 八德大船艦 第一展演廳
費用：免費, CSS 公司提供

### CDIB Innovation Accelerator Co., Ltd. 
費用：免費, AMIS 幫忙詢問

### Futureward
費用：4,000 /1hr 
網站： http://futureward.com/zh-hant/central/#function-room
敘述：
> 座落於台北市核心地帶，距離南京復興捷運站僅5分鐘路程，周遭鄰近交通主要幹道、飯店及商業區。我們的活動空間可容納近160人，並可提供桌椅、投影設備、也可調整燈光以滿足您的活動需求，適合舉行各種記者會、研討會、新品發表會或社群活動。
額外費用：
* 進場協助：NT$ 1,000/ 時
* 音響及視訊：NT$ 500/ 次
* 操作人員：NT$ 500/ 時

**Comment by yurenju** [comment]
Hook 測試

**Comment by willliw** [comment]
test

**Comment by yurenju** [comment]
Hook 測試

**Comment by yurenju** [comment]
今日miyachen 已經到 CDIB Innovation Accelerator 探勘，感謝！ 👍 

探勘感想如下：

> 我今天去CDIB Innovation Accelerator拍了一些照片, 給大家參考一下
> 場地能夠容納的人數是約120人左右, 沒有隨處可見的插頭可以使用,
> social area可以自己安排食物, 場地清潔要自己做
> 網路的部分需要的話要再問一下, 剛剛去沒有人在櫃檯
> 以11/25的日期為主, 目前確定可以用, AMIS這邊可以免費借場地
> 我覺得可以多看看, 因為他的social area是狹長型空間, 所以如果擺放食物, 人可以走的空間就變小了
> 然後會議室只能容納100出頭的人數, 人多的話也很難用站的
> 報到處那張照片我沒有拍得很好, 實際上左邊有一個凹進去的空間可以擺長桌子
> 有需要可以實際走一趟看看, 不過頗遠, 在南港軟體園區, 週末沒有開放


![conference_room_outside](https://user-images.githubusercontent.com/22155/32093390-b1072004-bb2e-11e7-95f7-0e8a85dc5387.JPG)
![max_event](https://user-images.githubusercontent.com/22155/32093391-b1320b66-bb2e-11e7-8541-532dd840f449.JPG)
![reception](https://user-images.githubusercontent.com/22155/32093393-b159d4de-bb2e-11e7-96db-840bed05bc67.jpg)
![social_area](https://user-images.githubusercontent.com/22155/32093394-b1817e26-bb2e-11e7-92a2-7c0b4ef30e8c.JPG)
![social_area2](https://user-images.githubusercontent.com/22155/32093395-b1ab4c38-bb2e-11e7-927e-5c486905689e.JPG)
![conference_room](https://user-images.githubusercontent.com/22155/32093396-b1d421d0-bb2e-11e7-9af8-0df3cf891f78.JPG)

**Comment by yurenju** [comment]
附上未來產房多功能活動空間的照片，並且更新相關訊息到 issue description

![image](https://user-images.githubusercontent.com/22155/32098734-3f186414-bb40-11e7-8f3c-1eec4b410e2d.png)
![image](https://user-images.githubusercontent.com/22155/32098745-46b53684-bb40-11e7-8a01-8c47b3b5f2fb.png)
![image](https://user-images.githubusercontent.com/22155/32098760-4f5bb6b4-bb40-11e7-8f7f-2c997d4c3fbd.png)

**Comment by yurenju** [comment]
目前 Ken 跟 @juinc 可以一起去場地探勘，目前我會先連絡這兩個場地未來產房 (futureward) 跟 CLBC，並原則上在晚上場地勘查。至於微軟我猜想是工作時間比較方便，但我還是會詢問一下他們能不能晚上六點後過去看看。

如果各位對於哪些場地還有想要探勘的請留言在這個 issue。

**Comment by yurenju** [comment]
* Futureward 未來產房預約在周一 7:00pm
* CLBC - email 詢問中，原則上希望可以排周一 8:00pm 或週二 7:00pm
* 微軟 - email 詢問中

**Comment by juincc0** [comment]
有個想法：
如果要增加講者跟聽眾互動，可以選空間小一點的場地，然後吃的很重要

**Comment by yurenju** [comment]
[off topic] 如果要增加互動，除了場地以外，也可以思考一下怎麼從議程安排。比如說安排一些以討論為基礎的議程。這在台灣的研討會比較少見，不過我在國外參加的 Web Summit 跟 Code for America 都有遇過，主持人基本上是提出一些問題，並且用一些機制帶領大家討論。比如說分四個群組，然後四個工作人員協助這四個群組一起想出一些意見，接下來在一起提出這些意見跟不同的群組之間討論。

不過這完全離題了 XDD

回到正題，我們可以在場地上選擇比較容易增進討論的場地，不過我也想多了解一下除了 @juinc 提出的選場地的想法外，大家還有什麼想法覺得怎樣的場地形式可以增進討論。除了場地的選擇外，也可以從場地布置下手。

**Comment by juincc0** [comment]
小朱上面提出的想法比較類似 workshop，但這種做法其實風險很高，主要考量兩點：
1. 我們不知道台灣 blockchain 社群的成熟程度 (或者可以說：不成熟)
2. 我們不知道講者的互動程度

所以安排workshop的結果有可能會很乾

我覺得保險牌是把tea break拉長，餐點好一點，場地好一點 (例如有不錯的景觀裝置或者沙發區)，讓大家感到愉悅放鬆，讓講者跟聽眾自由互動，或許會激發出不同的效果，我們也可以於事後徵詢講者的建議，也試探台灣的社群成熟度，有助下一次設計出更好的議程

但我相信某個程度的帶領是必要的，但可能不用到議程的形式

補充：酒精永遠是最好的破冰工具哈哈哈

**Comment by yurenju** [comment]
我們開另外一個 issue，然後我們把這些討論移過去好了。另外這些經驗也都是分享一下之前看過的做法，以我們現在的時間也不適合做這些相對來說太實驗性質的嘗試

**Comment by yurenju** [comment]
我把這些討論 copy 一份到 #6，有興趣的可以延續這些討論。不過原本的討論就留在這裡不刪了，脈絡比較清楚。

**Comment by yurenju** [comment]
更新目前的狀況一下。微軟目前因為原本的負責人目前不在台灣，改跟另外一位 Reneata 約今天下午三點。所以今天會有兩個場勘：微軟跟未來產房。

今天的場勘人員：
* [微軟](https://goo.gl/maps/LkjY4pAVkgC2) (下午三點)：我 (@yurenju)
* [未來產房 南京復興](https://goo.gl/maps/oG9xMKQEvdS2) (晚上七點)：我、 @quesalltime 跟 @juinc 跟陳保羅

未來產房的場勘，請大家七點直接在場地門口集合。

**更新**

因為打電話去未來產房發現她沒接到我們的預約，跟他們確認下班時間後改為 6:00 場勘。

**Comment by yurenju** [comment]
CLBC 大船艦場館 11/25 已經被預訂了，目前 CLBC 約一百人的場地只剩下 [德惠貳參](http://clbc.tw/t23eventspace/)。目前聯絡預約中，可能要週三才有辦法看場地。

考慮到時間因素，建議是先考慮其他場地，把這個的優先權排後面一點。

**Comment by yurenju** [comment]
更新一下今天看的三個場地個別的狀況。

### 微軟

微軟除了一樓門禁比較麻煩外，看起來場地是非常的好，而且除了會議室是三間會議室打通，場地大小充足外，另外也有額外的場地可以提供飲食（會議室內是嚴禁飲食的）。也是目前看到的場地最好的一個。

另外一方面有其他問題待解決，由於微軟的場地原本是預計提供給單純的社群活動使用，如果有贊助上擺攤或是收取門票的話他們很難跟公司與其他想要借用的社群交代。所以如果要借用微軟的場地則要考慮這些事情，或許用更正式的贊助方案，並且用贊助金額去借用其他場地比較合適。

### Mozilla Space

Mozilla Space 是今天第二間看的場地，也是這三間場地最小的一間。看起來頂多可以容納四十人，再多就會變得很擁擠了。除了 Mozilla Space 以外，還有另外一個小空間可供使用，不過總歸來說空間還是太小了，不適用這次的研討會。

### Futureward 未來產房

未來產房大小適中，擺滿椅子可以提供約一百三十人，空間上除了多功能會議廳外，外面也有擺設報到處以及攤位的空間。電源插座在會議室前面、後面跟兩旁牆壁都各有一些約十組，會需要用延長線擴增一些插座。至於網路在詢問下以前也有辦過類似的活動，看起來狀況還可以。

目前這三間最好的場地是微軟的場地，不過未來產房看起來也符合條件，也比較有彈性。晚點會附上照片（除了微軟的，因為當時正好有活動舉辦中）。

**Comment by yurenju** [comment]
一些照片，微軟因為場地正在使用中，就沒有拍照了。

### 未來產房

會議室內部，目前只擺了大概四十張椅子

![apc_1172](https://user-images.githubusercontent.com/22155/32181799-3d6fe726-bdd0-11e7-8427-993a946a1448.jpg)
![apc_1169](https://user-images.githubusercontent.com/22155/32181803-3d9d85b4-bdd0-11e7-9c95-e21d1092d497.jpg)
![apc_1170](https://user-images.githubusercontent.com/22155/32181804-3dca468a-bdd0-11e7-8737-e09bc94a50df.jpg)
![apc_1171](https://user-images.githubusercontent.com/22155/32181805-3df66904-bdd0-11e7-9ed6-342afb0d6fe8.jpg)

會議室外面，可以擺報到處以及廠商的攤位，但是可能頂多擺個一兩張長桌

![apc_1174](https://user-images.githubusercontent.com/22155/32181862-5ea2e3bc-bdd0-11e7-8b69-f4d140d300bc.jpg)

### Mozilla 

環境不錯，但是位置太少了。

![apc_1166](https://user-images.githubusercontent.com/22155/32181918-7d6e9ac0-bdd0-11e7-87f5-3ecdc7c84e57.jpg)
![apc_1167](https://user-images.githubusercontent.com/22155/32181919-7d9ca802-bdd0-11e7-8682-9f323c100c67.jpg)


![apc_1163](https://user-images.githubusercontent.com/22155/32181913-7cd47120-bdd0-11e7-8a64-37e48c8224cd.jpg)
![apc_1164](https://user-images.githubusercontent.com/22155/32181914-7d16d5d8-bdd0-11e7-9977-cd896f7958de.jpg)
![apc_1165](https://user-images.githubusercontent.com/22155/32181916-7d43a784-bdd0-11e7-8816-f3f803412cb7.jpg)

![apc_1162](https://user-images.githubusercontent.com/22155/32181912-7ca5a0f2-bdd0-11e7-9535-c97ed124e0aa.jpg)

**Comment by yurenju** [comment]
[預約用表單](https://docs.google.com/forms/d/e/1FAIpQLSfXsIT6SuBfAfN-4yLPDUfQqpK9-pE0fJy91iPsMDCHuV9mbA/viewform)

目前預估借用時間如下，今晚六點會跟未來產房預約：
* 租借場地：Function Room
* 活動名稱：BeyondBlock Taipei
* 活動類型：技術型研討會
* 借用日期：11/25 週六
* 進場時間（場佈）：8:00
* 活動開始時間：9:00
* 活動結束時間：19:00
* 撤場時間：20:00

預估花費：
* 場地費：36,000 元（假日每三個小時一萬元，每個小時 4000 元，進場/撤場費用每小時 1,000）
* 清潔費：1,000 元（50人以下$500，51-100人$1,000，以此類推）
* 音響及視訊：500 元 （500/ 次）
* 總花費：37,500 元

### 未來產房場地圖

我們借用的是 function room 長寬為 是 14.2M 長 x 11.6M 寬、外面接待區是 10.5M 長 x 5.5M 寬。

![event google form](https://user-images.githubusercontent.com/22155/32210242-8ec648be-be47-11e7-9510-2bddabd9a833.png)

**Comment by yurenju** [comment]
未來產房南京復興站的場地申請表單已送出。

**Comment by yurenju** [comment]
更新一下狀況，我方已簽名，接下來會
* 等對方簽名並回傳
* 匯款訂金

這兩個事項結束後就可以關閉這個 issue。
