### ISSUE TITLE
設計

### ISSUE THREAD

**Issue by juincc0** [EtherTW/beyondblock_taipei_2017#8]
[Logo repo](https://github.com/EtherTW/Logo)

## 衣服
數量？ 類型？（tshirt or polo）顏色？ 大小？ 預算？有倉庫？

**Comment by daubas** [comment]
需求是約200件（S／M／L／XL），黑白、白黑、黑灰（logo色／底）三種款式（分為會眾、工作人員、講者），圖樣用meetup的logo，布料就是一般活動衫（美國棉300g）。

**Comment by daubas** [comment]
目前需求為：
- 約200件（S／M／L／XL），
- 黑白、白黑、黑灰（logo色／底）三種款式（分為會眾、工作人員、講者）
- 圖樣用meetup的logo。
- 布料就是一般活動的短袖T桖。
- 圖案在胸口。

初步問了三家廠商（未包含運費），地點都在台北：

- DYC 吳先生 (02)23117506 價格為212元／件。
- MYIF 葉小姐 (02)33221332#23 價格約為170元／件，會打樣，11/3前要送電子檔。
- INIF (郵件聯絡) 價格約為170元／件，不打樣。

資訊可以直接google得到；
各家的布料不太一樣，1.會比較厚一點，
之前有配合1.過一切順利，
但後兩家也是蠻大的應該問題不大。

**Comment by daubas** [comment]
現在需要
1.確認工作人員、講者衣服的尺寸，會眾直接用常態分佈來估算件數。
2.三種顏色各對應到哪類參與者。
3.費用部分要從哪邊來。

**Comment by daubas** [comment]
更新一下，目前確定這次先不做衣服，
先只做貼紙。

**Comment by ChihChengLiang** [comment]
貼紙目前出了嗎？這裡我能接下處理。 @daubas

**Comment by daubas** [comment]
貼紙這部分就麻煩 @ChihChengLiang 處理了，目前這塊還沒進度

**Comment by ChihChengLiang** [comment]
貼紙搬到 #19 處理
